"""CSRF 미션 퀴즈 문항 은행 (50문항)."""

QUESTIONS = [
    {
        "id": "cs-01",
        "question": "CSRF의 정의로 가장 정확한 것은?",
        "options": [
            "피해자의 인증 상태를 악용해 의도치 않은 요청을 위조 실행시키는 취약점",
            "브라우저 스크립트 실행 취약점",
            "SQL 주입",
            "파일 업로드 취약점",
        ],
        "answer": 0,
        "explanation": "CSRF는 로그인된 피해자의 권한으로 공격자가 원하는 요청을 보내게 만든다.",
    },
    {
        "id": "cs-02",
        "question": "CSRF가 성립하는 핵심 전제는?",
        "options": [
            "서버가 느림",
            "브라우저가 쿠키(세션)를 요청에 자동으로 첨부함",
            "HTTPS 미사용",
            "자바스크립트 필수",
        ],
        "answer": 1,
        "explanation": "쿠키 자동 전송 특성 때문에 교차 사이트 요청에도 인증이 실린다.",
    },
    {
        "id": "cs-03",
        "question": "CSRF와 XSS의 핵심 차이는?",
        "options": [
            "CSRF가 스크립트 실행",
            "둘은 동일",
            "XSS는 스크립트 실행, CSRF는 인증된 요청 위조",
            "XSS가 요청 위조",
        ],
        "answer": 2,
        "explanation": "둘은 다른 문제이며, XSS로 CSRF 토큰을 탈취해 결합되기도 한다.",
    },
    {
        "id": "cs-04",
        "question": "DVWA CSRF 실습의 대상 기능은?",
        "options": [
            "이미지 업로드",
            "파일 업로드",
            "로그 검색",
            "비밀번호 변경",
        ],
        "answer": 3,
        "explanation": "DVWA CSRF는 비밀번호 변경 요청을 위조하는 시나리오다.",
    },
    {
        "id": "cs-05",
        "question": "DVWA CSRF Low 단계의 특징은?",
        "options": [
            "토큰·Referer 검사 없음 → 외부 폼으로 바로 변경",
            "토큰 필요",
            "Referer 검사",
            "현재 비밀번호 확인",
        ],
        "answer": 0,
        "explanation": "Low는 아무 방어가 없어 외부 폼 제출만으로 변경된다.",
    },
    {
        "id": "cs-06",
        "question": "DVWA CSRF Medium 단계의 방어는?",
        "options": [
            "CSRF 토큰",
            "Referer 헤더에 서버 호스트가 포함되는지 검사",
            "현재 비밀번호",
            "캡차",
        ],
        "answer": 1,
        "explanation": "Medium은 Referer에 호스트명이 있는지(stripos) 확인한다.",
    },
    {
        "id": "cs-07",
        "question": "Medium(Referer 검사)을 우회하는 방법은?",
        "options": [
            "캡차 우회",
            "토큰 추측",
            "Referer 값을 호스트명이 포함되도록 위조",
            "쿠키 삭제",
        ],
        "answer": 2,
        "explanation": "Referer는 조작 가능하거나 특정 경로 구성으로 우회될 수 있다.",
    },
    {
        "id": "cs-08",
        "question": "Referer 기반 CSRF 방어의 한계는?",
        "options": [
            "쿠키 손상",
            "항상 안전",
            "속도 저하",
            "Referer는 없거나 위조될 수 있어 신뢰도가 낮음",
        ],
        "answer": 3,
        "explanation": "Referer는 누락·위조 가능해 단독 방어로 약하다.",
    },
    {
        "id": "cs-09",
        "question": "DVWA CSRF High 단계의 방어는?",
        "options": [
            "Anti-CSRF 토큰(user_token) 검증",
            "Referer만",
            "캡차",
            "길이 제한",
        ],
        "answer": 0,
        "explanation": "High는 요청에 유효한 CSRF 토큰을 요구한다.",
    },
    {
        "id": "cs-10",
        "question": "High(토큰 검사)를 우회하려면 공격자는 무엇이 필요한가?",
        "options": [
            "쿠키만",
            "유효한 CSRF 토큰(예: XSS로 유출)",
            "서버 종료",
            "DNS 변경",
        ],
        "answer": 1,
        "explanation": "토큰을 알아야 하므로 보통 XSS 등으로 토큰을 탈취한다.",
    },
    {
        "id": "cs-11",
        "question": "DVWA CSRF Impossible 단계의 방어는?",
        "options": [
            "캡차만",
            "Referer만",
            "현재 비밀번호 재확인 + 토큰",
            "없음",
        ],
        "answer": 2,
        "explanation": "현재 비밀번호를 모르면 공격이 불가능하다.",
    },
    {
        "id": "cs-12",
        "question": "CSRF의 근본 방어로 가장 널리 쓰이는 것은?",
        "options": [
            "WAF만",
            "입력 길이 제한",
            "쿠키 암호화",
            "Anti-CSRF 토큰(동기화 토큰 패턴)",
        ],
        "answer": 3,
        "explanation": "요청마다 예측 불가한 토큰을 검증하는 것이 표준 방어다.",
    },
    {
        "id": "cs-13",
        "question": "Anti-CSRF 토큰이 방어가 되는 원리는?",
        "options": [
            "정상 페이지에만 심긴 비밀 값을 외부 공격자가 알 수 없어서",
            "쿠키를 암호화해서",
            "서버가 빨라서",
            "HTTPS라서",
        ],
        "answer": 0,
        "explanation": "교차 사이트 공격자는 토큰을 읽을 수 없어 요청을 완성하지 못한다.",
    },
    {
        "id": "cs-14",
        "question": "SameSite 쿠키 속성이 CSRF를 막는 원리는?",
        "options": [
            "쿠키를 암호화",
            "교차 사이트 요청에 쿠키를 보내지 않거나 제한함",
            "토큰을 생성",
            "캡차 표시",
        ],
        "answer": 1,
        "explanation": "SameSite=Lax/Strict는 교차 사이트 요청의 쿠키 전송을 제한한다.",
    },
    {
        "id": "cs-15",
        "question": "SameSite 설정값 중 교차 사이트 전송을 가장 강하게 막는 것은?",
        "options": [
            "None",
            "Lax",
            "Strict",
            "Default(미설정)",
        ],
        "answer": 2,
        "explanation": "Strict는 교차 사이트 요청에 쿠키를 전혀 보내지 않는다.",
    },
    {
        "id": "cs-16",
        "question": "CSRF 공격이 보통 노리는 요청 유형은?",
        "options": [
            "CSS 다운로드",
            "단순 조회(GET read-only)",
            "정적 이미지 로드",
            "상태를 바꾸는 요청(비밀번호 변경, 송금, 설정 변경)",
        ],
        "answer": 3,
        "explanation": "부작용이 있는 상태 변경 요청이 주요 표적이다.",
    },
    {
        "id": "cs-17",
        "question": "GET으로 상태 변경을 처리하면 CSRF에 특히 취약한 이유는?",
        "options": [
            "img/link 등으로 자동 요청이 쉬워져서",
            "느려서",
            "쿠키가 커서",
            "HTTPS라서",
        ],
        "answer": 0,
        "explanation": "GET 상태 변경은 `<img src>` 같은 수단으로 손쉽게 위조된다.",
    },
    {
        "id": "cs-18",
        "question": "CSRF 토큰은 어디에 담아 전송하는 것이 일반적인가?",
        "options": [
            "URL 경로명",
            "히든 폼 필드 또는 커스텀 헤더",
            "쿠키에만",
            "User-Agent",
        ],
        "answer": 1,
        "explanation": "폼 필드/헤더로 전송하며, 쿠키에만 두면(단독) 보호가 약하다.",
    },
    {
        "id": "cs-19",
        "question": "Double Submit Cookie 패턴이란?",
        "options": [
            "비밀번호 두 번 입력",
            "쿠키를 두 번 보냄",
            "쿠키와 요청 파라미터의 토큰 값을 대조",
            "토큰 두 개 생성",
        ],
        "answer": 2,
        "explanation": "쿠키의 토큰과 요청 본문/헤더의 토큰이 일치하는지 비교한다.",
    },
    {
        "id": "cs-20",
        "question": "CSRF 토큰의 요건으로 옳은 것은?",
        "options": [
            "로그에 기록",
            "짧고 고정",
            "URL에 노출",
            "예측 불가(충분한 엔트로피)하고 세션에 바인딩",
        ],
        "answer": 3,
        "explanation": "추측 불가하고 사용자/세션에 묶여야 안전하다.",
    },
    {
        "id": "cs-21",
        "question": "CSRF와 XSS가 결합되면 위험한 이유는?",
        "options": [
            "XSS로 토큰을 읽어 토큰 기반 방어까지 무력화",
            "서버가 느려짐",
            "DB 백업됨",
            "무관",
        ],
        "answer": 0,
        "explanation": "같은 출처에서 실행되는 XSS는 토큰을 탈취할 수 있다.",
    },
    {
        "id": "cs-22",
        "question": "CSRF 공격에 자바스크립트가 '반드시' 필요한가?",
        "options": [
            "그렇다",
            "아니다. 자동 제출 폼/이미지로도 가능",
            "GET만 가능",
            "쿠키가 없어야",
        ],
        "answer": 1,
        "explanation": "자동 submit 폼이나 img 태그 등으로 스크립트 없이도 가능하다.",
    },
    {
        "id": "cs-23",
        "question": "로그아웃 CSRF(강제 로그아웃)의 분류는?",
        "options": [
            "XSS",
            "조회 공격",
            "상태 변경 요청 위조의 일종",
            "SQLi",
        ],
        "answer": 2,
        "explanation": "로그아웃도 상태 변경이므로 CSRF 대상이 될 수 있다.",
    },
    {
        "id": "cs-24",
        "question": "CSRF 방어로 '충분하지 않은' 것은?",
        "options": [
            "민감 작업 재인증",
            "Anti-CSRF 토큰",
            "SameSite 쿠키",
            "Referer 검사만",
        ],
        "answer": 3,
        "explanation": "Referer는 위조·누락 가능해 단독으로 불충분하다.",
    },
    {
        "id": "cs-25",
        "question": "민감 작업(비밀번호/결제)에서 '재인증'이 방어가 되는 이유는?",
        "options": [
            "공격자가 모르는 현재 비밀번호/추가 인증을 요구",
            "속도 때문",
            "쿠키 때문",
            "CSS 때문",
        ],
        "answer": 0,
        "explanation": "현재 비밀번호 확인 등은 공격자가 완성할 수 없게 만든다.",
    },
    {
        "id": "cs-26",
        "question": "DVWA CSRF Low에서 외부 공격 페이지의 전형적 형태는?",
        "options": [
            "SQL 쿼리",
            "피해자 클릭/방문 시 비밀번호 변경 요청을 자동 제출하는 폼",
            "이미지 파일",
            "CSS 파일",
        ],
        "answer": 1,
        "explanation": "숨은 폼이 자동 제출되어 피해자 권한으로 변경이 일어난다.",
    },
    {
        "id": "cs-27",
        "question": "CSRF 토큰을 URL 쿼리스트링에 노출하면 안 되는 이유는?",
        "options": [
            "쿠키 때문",
            "느려서",
            "로그/Referer/히스토리로 유출될 수 있어서",
            "CSS 때문",
        ],
        "answer": 2,
        "explanation": "URL은 여러 곳에 기록되어 토큰이 새어나갈 수 있다.",
    },
    {
        "id": "cs-28",
        "question": "CSRF 방어에서 'per-request vs per-session 토큰'의 차이는?",
        "options": [
            "쿠키 설정",
            "같은 말",
            "둘 다 무의미",
            "요청마다 vs 세션당 토큰 — 둘 다 유효, 전자가 더 엄격",
        ],
        "answer": 3,
        "explanation": "둘 다 쓰이며 요청별 토큰이 더 엄격하지만 구현 비용이 크다.",
    },
    {
        "id": "cs-29",
        "question": "API(JSON) 요청의 CSRF 방어로 적절한 것은?",
        "options": [
            "커스텀 헤더 요구 + SameSite + 토큰",
            "아무 것도 필요 없음",
            "GET으로 처리",
            "쿠키만 사용",
        ],
        "answer": 0,
        "explanation": "커스텀 헤더(교차 출처에서 임의 설정 어려움)와 토큰/SameSite를 병행한다.",
    },
    {
        "id": "cs-30",
        "question": "CSRF가 'Confused Deputy(혼란한 대리인)' 문제로 불리는 이유는?",
        "options": [
            "대리 서버 때문",
            "서버가 피해자의 정당한 요청으로 오인해 대신 수행해서",
            "프록시 때문",
            "쿠키 때문",
        ],
        "answer": 1,
        "explanation": "서버가 인증된 요청을 신뢰해 공격자 의도를 대신 실행한다.",
    },
    {
        "id": "cs-31",
        "question": "SameSite=None을 쓸 때 필수 조건은?",
        "options": [
            "토큰 금지",
            "HTTP만",
            "Secure 속성(HTTPS)과 함께 사용",
            "쿠키 평문",
        ],
        "answer": 2,
        "explanation": "SameSite=None은 Secure와 함께여야 하며 교차 전송을 허용한다.",
    },
    {
        "id": "cs-32",
        "question": "다음 중 CSRF 완화에 직접 기여하지 않는 것은?",
        "options": [
            "재인증",
            "Anti-CSRF 토큰",
            "SameSite 쿠키",
            "이미지 썸네일 캐시",
        ],
        "answer": 3,
        "explanation": "썸네일 캐시는 성능 요소로 CSRF와 무관하다.",
    },
    {
        "id": "cs-33",
        "question": "CSRF 토큰 검증 실패 시 서버의 올바른 동작은?",
        "options": [
            "요청 거부(상태 변경 안 함)",
            "그래도 처리",
            "로그만 남기고 처리",
            "쿠키 삭제",
        ],
        "answer": 0,
        "explanation": "토큰이 없거나 불일치하면 요청을 거부해야 한다.",
    },
    {
        "id": "cs-34",
        "question": "CSRF가 'Stored(저장형)'처럼 전파되는 경우는?",
        "options": [
            "항상 1명만",
            "XSS/저장형 콘텐츠와 결합해 다수에게 자동 요청 유발",
            "서버만",
            "무관",
        ],
        "answer": 1,
        "explanation": "저장형 XSS와 결합하면 광범위하게 위조 요청이 발생할 수 있다.",
    },
    {
        "id": "cs-35",
        "question": "CSRF 방어에서 'SameSite=Lax'의 기본 동작은?",
        "options": [
            "모든 요청 허용",
            "모든 요청 차단",
            "대부분의 교차 사이트 POST에 쿠키 미전송(일부 GET 예외)",
            "쿠키 암호화",
        ],
        "answer": 2,
        "explanation": "Lax는 교차 사이트 상태 변경(POST 등)에 쿠키를 보내지 않는다.",
    },
    {
        "id": "cs-36",
        "question": "다음 중 CSRF 취약 가능성이 가장 높은 설계는?",
        "options": [
            "커스텀 헤더 검증",
            "토큰+SameSite 적용",
            "재인증 적용",
            "토큰 없이 쿠키 인증만으로 상태 변경 처리",
        ],
        "answer": 3,
        "explanation": "쿠키만 신뢰하고 토큰이 없으면 전형적 CSRF 취약 설계다.",
    },
    {
        "id": "cs-37",
        "question": "CSRF 점검 시 확인할 핵심은?",
        "options": [
            "상태 변경 요청에 예측 불가 토큰 검증이 있는지",
            "디스크 용량",
            "CPU 온도",
            "폰트",
        ],
        "answer": 0,
        "explanation": "상태 변경 요청의 토큰 검증 유무가 핵심이다.",
    },
    {
        "id": "cs-38",
        "question": "CSRF 토큰을 '세션에 바인딩'해야 하는 이유는?",
        "options": [
            "속도 때문",
            "다른 사용자/세션의 토큰 재사용을 막기 위해",
            "쿠키 때문",
            "CSS 때문",
        ],
        "answer": 1,
        "explanation": "세션 바인딩으로 토큰 도용·재사용을 방지한다.",
    },
    {
        "id": "cs-39",
        "question": "CSRF 방어로 'Origin 헤더 검증'의 장점은?",
        "options": [
            "암호화됨",
            "항상 존재",
            "Referer보다 신뢰도가 높아 교차 출처 판별에 유용",
            "토큰 대체 불필요",
        ],
        "answer": 2,
        "explanation": "Origin은 교차 출처 판별에 유용하지만 토큰과 병행이 권장된다.",
    },
    {
        "id": "cs-40",
        "question": "다음 중 CSRF와 가장 거리가 먼 방어는?",
        "options": [
            "재인증",
            "Anti-CSRF 토큰",
            "SameSite",
            "출력 HTML 인코딩",
        ],
        "answer": 3,
        "explanation": "출력 인코딩은 XSS 방어로 CSRF와 직접 관련이 적다.",
    },
    {
        "id": "cs-41",
        "question": "CSRF 토큰이 있어도 XSS가 있으면 위험한 이유는?",
        "options": [
            "XSS로 DOM에서 토큰을 읽어 위조 요청을 완성할 수 있어서",
            "토큰이 커져서",
            "서버가 느려서",
            "무관",
        ],
        "answer": 0,
        "explanation": "같은 출처 XSS는 토큰 접근이 가능해 방어를 무력화한다.",
    },
    {
        "id": "cs-42",
        "question": "결제/송금 기능의 CSRF 방어로 가장 바람직한 조합은?",
        "options": [
            "토큰만",
            "토큰 + SameSite + 민감작업 재인증",
            "SameSite만",
            "없음",
        ],
        "answer": 1,
        "explanation": "고위험 작업은 여러 방어를 중첩한다.",
    },
    {
        "id": "cs-43",
        "question": "CSRF 공격 페이지가 '피해자 브라우저'에서 실행되는 이유는?",
        "options": [
            "DB에서 실행돼서",
            "서버에서 실행돼서",
            "피해자가 로그인된 세션으로 요청을 보내야 하므로",
            "프록시에서",
        ],
        "answer": 2,
        "explanation": "피해자의 인증 쿠키가 실려야 하므로 피해자 브라우저에서 요청이 나간다.",
    },
    {
        "id": "cs-44",
        "question": "다음 중 CSRF 토큰 구현의 '안티패턴'은?",
        "options": [
            "토큰 세션 바인딩",
            "세션별 무작위 토큰",
            "요청별 토큰",
            "모든 사용자가 같은 고정 토큰 사용",
        ],
        "answer": 3,
        "explanation": "고정/공유 토큰은 예측·재사용이 가능해 의미가 없다.",
    },
    {
        "id": "cs-45",
        "question": "CSRF 방어 적용 후 재검증 시 확인할 점은?",
        "options": [
            "모든 상태 변경 엔드포인트가 토큰을 검증하는지",
            "조회 API만",
            "CPU만",
            "쿠키만",
        ],
        "answer": 0,
        "explanation": "누락된 상태 변경 엔드포인트가 없는지 전수 확인한다.",
    },
    {
        "id": "cs-46",
        "question": "프레임워크 내장 CSRF 보호(예: Flask-WTF)의 역할은?",
        "options": [
            "쿠키 암호화",
            "폼/요청에 토큰을 자동 생성·검증",
            "SQL 생성",
            "이미지 처리",
        ],
        "answer": 1,
        "explanation": "프레임워크 보호 기능으로 토큰 처리를 표준화한다.",
    },
    {
        "id": "cs-47",
        "question": "CSRF가 'SOP(동일 출처 정책)'로 완전히 막히지 않는 이유는?",
        "options": [
            "쿠키 때문만",
            "SOP가 없어서",
            "요청 전송 자체는 교차 출처에서도 가능(응답 읽기만 제한)",
            "HTTPS 때문",
        ],
        "answer": 2,
        "explanation": "SOP는 응답 읽기를 막지만 요청 전송과 부작용은 일어날 수 있다.",
    },
    {
        "id": "cs-48",
        "question": "다음 중 CSRF 위험을 '낮추는' 설계는?",
        "options": [
            "쿠키만 신뢰",
            "상태 변경을 GET으로",
            "토큰 생략",
            "상태 변경은 POST + 토큰 + SameSite",
        ],
        "answer": 3,
        "explanation": "메서드 구분과 토큰/SameSite 병행이 바람직하다.",
    },
    {
        "id": "cs-49",
        "question": "CSRF 종합 방어로 가장 올바른 조합은?",
        "options": [
            "Anti-CSRF 토큰 + SameSite 쿠키 + 민감작업 재인증(+Origin 검증)",
            "Referer만",
            "길이 제한만",
            "HTTPS만",
        ],
        "answer": 0,
        "explanation": "토큰을 핵심으로 SameSite·재인증 등을 병행하는 심층 방어.",
    },
    {
        "id": "cs-50",
        "question": "CSRF를 한 문장으로 요약하면?",
        "options": [
            "브라우저 스크립트 실행 문제",
            "피해자의 인증 상태를 악용한 요청 위조이며 토큰·SameSite로 막는다",
            "SQL 주입 문제",
            "파일 실행 문제",
        ],
        "answer": 1,
        "explanation": "인증된 요청 위조가 핵심이며 토큰/SameSite가 주요 방어다.",
    },
]
