"""SQL Injection (Blind) 미션 퀴즈 문항 은행 (50문항)."""

QUESTIONS = [
    {
        "id": "sb-01",
        "question": "Blind SQL Injection의 정의는?",
        "options": [
            "결과가 직접 안 보이고 참/거짓·시간차 등 간접 신호로 데이터를 추론하는 SQLi",
            "브라우저 스크립트 실행",
            "파일 업로드 취약점",
            "쿠키 위조",
        ],
        "answer": 0,
        "explanation": "조회 결과가 노출되지 않아도 응답 차이로 데이터를 알아낸다.",
    },
    {
        "id": "sb-02",
        "question": "Boolean-based Blind의 핵심 원리는?",
        "options": [
            "오류 메시지 분석",
            "조건의 참/거짓에 따라 응답이 달라지는 것을 관찰",
            "응답 지연 측정",
            "쿠키 변화",
        ],
        "answer": 1,
        "explanation": "참일 때와 거짓일 때 응답(예: exists/missing)이 달라지는 것을 이용한다.",
    },
    {
        "id": "sb-03",
        "question": "Time-based Blind의 핵심 원리는?",
        "options": [
            "쿠키 변화",
            "오류 메시지",
            "참일 때 의도적 지연(SLEEP 등)으로 참/거짓 구분",
            "CSS 변화",
        ],
        "answer": 2,
        "explanation": "응답이 보이지 않을 때 SLEEP으로 시간 차이를 만들어 판별한다.",
    },
    {
        "id": "sb-04",
        "question": "Blind SQLi가 일반 SQLi보다 '느린' 이유는?",
        "options": [
            "브라우저 때문",
            "DB가 느려서",
            "네트워크가 느려서",
            "한 글자씩 참/거짓을 반복 질의해 추출하기 때문",
        ],
        "answer": 3,
        "explanation": "문자 단위로 조건을 바꿔가며 다수 요청을 보내 추출한다.",
    },
    {
        "id": "sb-05",
        "question": "`SUBSTR(password,1,1)='a'` 조건의 의미는?",
        "options": [
            "비밀번호 첫 글자가 'a'인지 묻는 조건",
            "비밀번호 길이",
            "비밀번호 삭제",
            "비밀번호 암호화",
        ],
        "answer": 0,
        "explanation": "SUBSTR로 특정 위치 글자를 잘라 비교해 참/거짓을 얻는다.",
    },
    {
        "id": "sb-06",
        "question": "Blind 추출을 '스무고개'에 비유하는 이유는?",
        "options": [
            "질문이 20개라서",
            "예/아니오(참/거짓) 질문 반복으로 값을 좁혀가서",
            "운에 의존해서",
            "답이 숨겨져서",
        ],
        "answer": 1,
        "explanation": "참/거짓만으로 한 글자씩 확정하는 과정이 스무고개와 같다.",
    },
    {
        "id": "sb-07",
        "question": "DVWA Blind에서 응답으로 주어지는 전형적 메시지는?",
        "options": [
            "SQL 쿼리문",
            "비밀번호 전체",
            "User ID exists / is MISSING",
            "서버 로그",
        ],
        "answer": 2,
        "explanation": "결과 데이터 대신 존재 여부(exists/missing)만 알려준다.",
    },
    {
        "id": "sb-08",
        "question": "DVWA Blind에서 admin은 보통 어떤 user_id인가?",
        "options": [
            "admin이라는 문자열",
            "999",
            "0",
            "1",
        ],
        "answer": 3,
        "explanation": "DVWA 기본 데이터에서 admin의 user_id는 1이다.",
    },
    {
        "id": "sb-09",
        "question": "`1' AND SUBSTR(password,1,1)='a' -- ` 가 참이면?",
        "options": [
            "user_id=1(admin)의 비밀번호 첫 글자가 'a'",
            "비밀번호가 삭제됨",
            "서버 종료",
            "세션 만료",
        ],
        "answer": 0,
        "explanation": "admin 행 조건에 글자 조건을 AND로 걸어 참/거짓을 얻는다.",
    },
    {
        "id": "sb-10",
        "question": "DVWA Blind Medium의 특징과 공략은?",
        "options": [
            "자유 텍스트",
            "숫자 컨텍스트 드롭다운 → 요청 변조로 주입",
            "파일 업로드",
            "쿠키",
        ],
        "answer": 1,
        "explanation": "Medium은 드롭다운+숫자라 요청을 변조해 서브쿼리 등으로 주입한다.",
    },
    {
        "id": "sb-11",
        "question": "DVWA Blind High에서 LIMIT 1을 다루는 방법은?",
        "options": [
            "서버 종료",
            "쿠키 변조",
            "주석(--)으로 제거하거나 조건으로 참/거짓만 확인",
            "UNION 금지",
        ],
        "answer": 2,
        "explanation": "참/거짓만 보면 되므로 주석으로 뒷부분을 정리해 판별한다.",
    },
    {
        "id": "sb-12",
        "question": "DVWA Blind Impossible 방어는?",
        "options": [
            "쿠키 암호화",
            "블랙리스트",
            "길이 제한만",
            "is_numeric + 파라미터 바인딩",
        ],
        "answer": 3,
        "explanation": "숫자 검증과 바인딩으로 주입 자체를 막는다.",
    },
    {
        "id": "sb-13",
        "question": "Blind SQLi의 근본 방어는?",
        "options": [
            "파라미터 바인딩(Prepared Statement)",
            "응답 메시지 숨김만",
            "WAF만",
            "길이 제한만",
        ],
        "answer": 0,
        "explanation": "다른 SQLi와 동일하게 바인딩이 근본 방어다.",
    },
    {
        "id": "sb-14",
        "question": "Boolean-based보다 Time-based가 더 까다로운 이유는?",
        "options": [
            "쿼리가 길어서",
            "네트워크 지연 노이즈 때문에 판별이 불안정",
            "쿠키가 필요해서",
            "DB가 달라서",
        ],
        "answer": 1,
        "explanation": "지연 관찰은 네트워크 변동에 취약해 더 느리고 불안정하다.",
    },
    {
        "id": "sb-15",
        "question": "응답 차이를 줄여도 Blind를 완전히 막지 못하는 이유는?",
        "options": [
            "DB가 막는다",
            "항상 막힌다",
            "시간 기반 등 다른 측면 채널이 남을 수 있어 바인딩이 필요",
            "쿠키가 막는다",
        ],
        "answer": 2,
        "explanation": "메시지 통일만으로는 time-based가 남으므로 근본은 바인딩이다.",
    },
    {
        "id": "sb-16",
        "question": "Blind SQLi 자동화에 흔히 쓰는 도구는?",
        "options": [
            "Burp Repeater만",
            "nmap",
            "Wireshark",
            "sqlmap",
        ],
        "answer": 3,
        "explanation": "sqlmap은 blind 추출을 자동화한다.",
    },
    {
        "id": "sb-17",
        "question": "Blind에서 '응답 지연 임계값'을 두는 이유는?",
        "options": [
            "SLEEP 유무를 안정적으로 판별하기 위해",
            "서버 보호",
            "쿠키 보호",
            "CSS 때문",
        ],
        "answer": 0,
        "explanation": "지연 시간 기준으로 참/거짓을 구분하려고 임계값을 쓴다.",
    },
    {
        "id": "sb-18",
        "question": "요청 속도 제한(rate limit)이 Blind 공격에 주는 영향은?",
        "options": [
            "완전 차단",
            "대량 반복 질의를 늦춰 자동 추출을 어렵게 함(보조 방어)",
            "무관",
            "속도 향상",
        ],
        "answer": 1,
        "explanation": "반복 요청이 많은 blind 특성상 rate limit이 완화에 도움(보조)된다.",
    },
    {
        "id": "sb-19",
        "question": "Blind 추출 대상의 예로 적절한 것은?",
        "options": [
            "이미지 크기",
            "CSS 색상",
            "admin 비밀번호, DB 버전, 테이블명 등",
            "폰트",
        ],
        "answer": 2,
        "explanation": "참/거짓으로 임의 문자열(비밀번호 등)을 한 글자씩 추출한다.",
    },
    {
        "id": "sb-20",
        "question": "`AND 1=1` 과 `AND 1=2` 로 먼저 확인하는 것은?",
        "options": [
            "DNS",
            "서버 속도",
            "쿠키 상태",
            "참/거짓 응답 차이가 실제로 나타나는지(주입 가능 여부)",
        ],
        "answer": 3,
        "explanation": "참 조건과 거짓 조건의 응답 차이로 blind 가능성을 확인한다.",
    },
    {
        "id": "sb-21",
        "question": "Blind SQLi가 '일반 SQLi보다 한 단계 위'로 분류되는 이유는?",
        "options": [
            "결과가 안 보여 추출이 더 복잡/느리기 때문",
            "항상 실패해서",
            "브라우저 때문",
            "쿠키 때문",
        ],
        "answer": 0,
        "explanation": "직접 출력이 없어 간접 신호로 추론해야 하므로 난도가 높다.",
    },
    {
        "id": "sb-22",
        "question": "이진 탐색(binary search)을 Blind에 쓰는 이유는?",
        "options": [
            "서버 보호",
            "글자 ASCII 범위를 반씩 좁혀 질의 횟수를 줄이려고",
            "쿠키 절약",
            "CSS 때문",
        ],
        "answer": 1,
        "explanation": "`> , <` 비교로 범위를 반분하면 요청 수를 크게 줄인다.",
    },
    {
        "id": "sb-23",
        "question": "DVWA Blind에서 'exists'가 뜨면 의미는?",
        "options": [
            "세션 만료",
            "서버 오류",
            "주입한 조건이 참(조건을 만족하는 행 존재)",
            "쿠키 변경",
        ],
        "answer": 2,
        "explanation": "조건을 만족하는 행이 있으면 exists로 참을 나타낸다.",
    },
    {
        "id": "sb-24",
        "question": "Blind 방어에서 '상세 오류 숨김'의 한계는?",
        "options": [
            "쿠키 손상",
            "완전 방어",
            "성능 저하",
            "참/거짓·시간 채널이 남아 근본 방어가 아님",
        ],
        "answer": 3,
        "explanation": "오류를 숨겨도 boolean/time 채널이 남는다.",
    },
    {
        "id": "sb-25",
        "question": "Blind SQLi와 일반 SQLi의 공통 근본 원인은?",
        "options": [
            "입력이 쿼리 구조를 바꿀 수 있음",
            "느린 네트워크",
            "큰 이미지",
            "긴 쿠키",
        ],
        "answer": 0,
        "explanation": "둘 다 데이터/명령 미분리가 원인이다.",
    },
    {
        "id": "sb-26",
        "question": "다음 중 Blind 추출 성공을 좌우하는 핵심 신호는?",
        "options": [
            "HTTP 메서드",
            "조건에 따른 응답(참/거짓 또는 지연) 차이",
            "쿠키 수",
            "폰트",
        ],
        "answer": 1,
        "explanation": "조건별 응답 차이가 추출의 기반이다.",
    },
    {
        "id": "sb-27",
        "question": "`ORD/ASCII` 함수를 Blind에서 쓰는 목적은?",
        "options": [
            "정렬",
            "암호화",
            "글자를 숫자로 바꿔 범위 비교(이진 탐색)에 활용",
            "삭제",
        ],
        "answer": 2,
        "explanation": "문자 코드값을 비교해 효율적으로 추출한다.",
    },
    {
        "id": "sb-28",
        "question": "Blind 공격을 어렵게 하는 '응답 일관화'란?",
        "options": [
            "CSS 통일",
            "모든 요청 차단",
            "쿠키 통일",
            "참/거짓 모두 동일한 응답을 주려는 시도(보조)",
        ],
        "answer": 3,
        "explanation": "응답을 같게 만들면 boolean 신호를 줄이지만 time 채널은 남는다.",
    },
    {
        "id": "sb-29",
        "question": "다음 중 Blind SQLi 방어로 가장 올바른 것은?",
        "options": [
            "파라미터 바인딩 + (보조)오류 숨김·rate limit",
            "WAF만",
            "HTTPS만",
            "길이 제한만",
        ],
        "answer": 0,
        "explanation": "바인딩이 핵심, 나머지는 보조다.",
    },
    {
        "id": "sb-30",
        "question": "Blind에서 서브쿼리 `(SELECT SUBSTR(password,1,1) FROM users WHERE user='admin')` 를 쓰는 이유는?",
        "options": [
            "성능 향상",
            "특정 사용자(admin)의 값을 조건에 끌어오기 위해",
            "쿠키 조회",
            "로그 조회",
        ],
        "answer": 1,
        "explanation": "서브쿼리로 원하는 레코드의 값을 조건에 넣어 참/거짓을 얻는다.",
    },
    {
        "id": "sb-31",
        "question": "숫자 컨텍스트 Blind(Medium)에서 `0 OR (조건)` 형태를 쓰는 이유는?",
        "options": [
            "쿠키 변조",
            "서버 종료",
            "따옴표 없이 조건을 OR로 붙여 참/거짓을 유도",
            "정렬",
        ],
        "answer": 2,
        "explanation": "숫자 컨텍스트라 따옴표 없이 OR 조건으로 주입한다.",
    },
    {
        "id": "sb-32",
        "question": "Blind SQLi 점검 시 '거짓 양성'을 줄이는 방법은?",
        "options": [
            "CPU 확인",
            "한 번만 테스트",
            "쿠키 확인",
            "동일 조건 반복·대조 요청으로 응답 차이를 검증",
        ],
        "answer": 3,
        "explanation": "노이즈가 있으므로 반복·대조로 신뢰도를 높인다.",
    },
    {
        "id": "sb-33",
        "question": "다음 중 Blind SQLi와 가장 거리가 먼 방어는?",
        "options": [
            "이미지 재인코딩",
            "파라미터 바인딩",
            "오류 일반화",
            "rate limit",
        ],
        "answer": 0,
        "explanation": "이미지 재인코딩은 파일 업로드 방어다.",
    },
    {
        "id": "sb-34",
        "question": "Blind 공격이 성공했을 때의 결과는?",
        "options": [
            "서버 파괴",
            "보이지 않던 데이터(비밀번호 등)를 복원",
            "CSS 변경",
            "폰트 변경",
        ],
        "answer": 1,
        "explanation": "간접 신호만으로 숨은 데이터를 알아낸다.",
    },
    {
        "id": "sb-35",
        "question": "Time-based를 탐지/완화하는 운영 신호는?",
        "options": [
            "폰트 크기",
            "쿠키 수",
            "비정상적으로 긴 쿼리 실행/반복 패턴 모니터링",
            "이미지 수",
        ],
        "answer": 2,
        "explanation": "지연 유발 쿼리와 반복 패턴을 모니터링해 탐지한다.",
    },
    {
        "id": "sb-36",
        "question": "Blind SQLi에서 '참 조건'을 만드는 가장 단순한 예는?",
        "options": [
            "AND 0",
            "AND 1=2",
            "AND 'a'='b'",
            "AND 1=1",
        ],
        "answer": 3,
        "explanation": "1=1은 항상 참이다.",
    },
    {
        "id": "sb-37",
        "question": "Blind SQLi에서 '거짓 조건'의 예는?",
        "options": [
            "AND 1=2",
            "AND 1=1",
            "OR 1=1",
            "AND 'x'='x'",
        ],
        "answer": 0,
        "explanation": "1=2는 항상 거짓이다.",
    },
    {
        "id": "sb-38",
        "question": "Blind 추출 길이를 먼저 알아내려면?",
        "options": [
            "서버 재시작",
            "LENGTH(password)=n 조건으로 참이 되는 n 탐색",
            "쿠키 조회",
            "CPU 측정",
        ],
        "answer": 1,
        "explanation": "LENGTH 비교로 대상 문자열 길이를 먼저 확정한다.",
    },
    {
        "id": "sb-39",
        "question": "Blind SQLi 방어로 '충분하지 않은' 것은?",
        "options": [
            "최소 권한",
            "파라미터 바인딩",
            "응답 메시지만 통일",
            "입력 검증 병행",
        ],
        "answer": 2,
        "explanation": "메시지 통일만으로는 time-based가 남는다.",
    },
    {
        "id": "sb-40",
        "question": "DVWA Blind에서 비밀번호를 다 추출한 뒤 하는 일은?",
        "options": [
            "쿠키 삭제",
            "서버 종료",
            "DB 삭제",
            "추출한 값을 제출해 성공 판정을 받음(실습 특성)",
        ],
        "answer": 3,
        "explanation": "실습에서는 추출한 비밀번호를 제출해 성공을 확인한다.",
    },
    {
        "id": "sb-41",
        "question": "Blind SQLi가 가능한데도 데이터가 '화면에 안 보이는' 이유는?",
        "options": [
            "애플리케이션이 결과 대신 상태만 출력하기 때문",
            "DB가 비어서",
            "HTTPS 때문",
            "쿠키 때문",
        ],
        "answer": 0,
        "explanation": "결과를 숨기고 상태(exists 등)만 반환하는 설계 때문이다.",
    },
    {
        "id": "sb-42",
        "question": "Blind 추출 효율을 높이는 조건 비교 연산자는?",
        "options": [
            "`=`만",
            "`>`, `<` (범위 분할)",
            "`LIKE`만",
            "`!=`만",
        ],
        "answer": 1,
        "explanation": "부등호로 이진 탐색하면 질의 수가 크게 준다.",
    },
    {
        "id": "sb-43",
        "question": "Blind SQLi와 일반 SQLi 모두에 효과적인 코드 패턴은?",
        "options": [
            "f-string 삽입",
            "문자열 결합",
            "플레이스홀더 바인딩",
            "% 포매팅",
        ],
        "answer": 2,
        "explanation": "바인딩이 모든 SQLi에 공통으로 효과적이다.",
    },
    {
        "id": "sb-44",
        "question": "Blind SQLi에서 '측면 채널(side channel)'의 예는?",
        "options": [
            "이미지",
            "CSS 색상",
            "폰트",
            "응답 길이/시간/상태 코드 차이",
        ],
        "answer": 3,
        "explanation": "길이·시간·상태 등 간접 신호가 측면 채널이다.",
    },
    {
        "id": "sb-45",
        "question": "다음 중 Blind SQLi 완화에 직접 기여하지 않는 것은?",
        "options": [
            "CDN 캐시 TTL 조정",
            "파라미터 바인딩",
            "rate limit",
            "오류 일반화",
        ],
        "answer": 0,
        "explanation": "CDN TTL은 성능 요소로 무관하다.",
    },
    {
        "id": "sb-46",
        "question": "Blind SQLi가 특히 위험한 데이터는?",
        "options": [
            "공개 공지사항",
            "자격 증명·개인정보 등 민감 정보",
            "정적 이미지",
            "CSS",
        ],
        "answer": 1,
        "explanation": "숨겨진 민감 데이터를 추출하는 데 쓰인다.",
    },
    {
        "id": "sb-47",
        "question": "Blind 추출 도중 'rate limit 429'를 만나면 의미는?",
        "options": [
            "서버 다운",
            "성공",
            "요청이 많아 일시 차단(완화 방어 작동)",
            "쿠키 만료",
        ],
        "answer": 2,
        "explanation": "과도한 반복 요청을 제한하는 방어가 작동한 것이다.",
    },
    {
        "id": "sb-48",
        "question": "Blind SQLi 방어 설계의 핵심 우선순위는?",
        "options": [
            "우선 길이 제한",
            "우선 WAF",
            "우선 HTTPS",
            "우선 바인딩, 그다음 오류/응답/속도 보조",
        ],
        "answer": 3,
        "explanation": "바인딩이 1순위, 나머지는 심층 보조다.",
    },
    {
        "id": "sb-49",
        "question": "Blind SQLi 종합 방어로 가장 올바른 조합은?",
        "options": [
            "파라미터 바인딩 + 오류 일반화 + rate limit + 최소 권한",
            "WAF만",
            "HTTPS만",
            "메시지 통일만",
        ],
        "answer": 0,
        "explanation": "바인딩을 핵심으로 보조 수단을 병행한다.",
    },
    {
        "id": "sb-50",
        "question": "Blind SQL Injection을 한 문장으로 요약하면?",
        "options": [
            "브라우저 스크립트 문제",
            "결과가 안 보여도 참/거짓·시간차로 데이터를 추론하는 SQLi이며 바인딩으로 막는다",
            "파일 실행 문제",
            "쿠키 위조 문제",
        ],
        "answer": 1,
        "explanation": "간접 신호 추론이 특징이며 근본 방어는 바인딩이다.",
    },
]
