"""SQL Injection 미션 퀴즈 문항 은행 (50문항)."""

QUESTIONS = [
    {
        "id": "sq-01",
        "question": "SQL Injection의 정의로 가장 정확한 것은?",
        "options": [
            "사용자 입력이 SQL 쿼리 구조의 일부로 해석·실행되는 취약점",
            "브라우저 스크립트 실행 취약점",
            "OS 명령 실행 취약점",
            "파일 업로드 취약점",
        ],
        "answer": 0,
        "explanation": "입력이 쿼리에 그대로 결합되어 쿼리의 의미를 바꿀 때 발생한다.",
    },
    {
        "id": "sq-02",
        "question": "SQLi의 근본 원인은?",
        "options": [
            "HTTPS 미사용",
            "데이터와 명령(쿼리 구조)이 분리되지 않음",
            "쿠키 저장",
            "느린 네트워크",
        ],
        "answer": 1,
        "explanation": "입력(데이터)이 쿼리(명령)의 구조를 바꿀 수 있을 때 생긴다.",
    },
    {
        "id": "sq-03",
        "question": "`' OR '1'='1` 가 인증 우회에 쓰이는 원리는?",
        "options": [
            "쿠키를 변조",
            "서버를 느리게 함",
            "항상 참인 조건을 만들어 WHERE 필터를 무력화",
            "DNS 변경",
        ],
        "answer": 2,
        "explanation": "조건이 항상 참이 되어 모든 행이 선택되거나 인증이 통과된다.",
    },
    {
        "id": "sq-04",
        "question": "UNION 기반 SQLi의 목적은?",
        "options": [
            "CSS 변경",
            "서버 종료",
            "쿠키 탈취",
            "다른 테이블/컬럼의 데이터를 원래 결과에 이어 붙여 유출",
        ],
        "answer": 3,
        "explanation": "UNION SELECT로 추가 쿼리 결과를 합쳐 임의 데이터를 꺼낸다.",
    },
    {
        "id": "sq-05",
        "question": "UNION SELECT 사용 시 반드시 맞춰야 하는 것은?",
        "options": [
            "컬럼 개수(및 호환 타입)",
            "서버 시간",
            "쿠키 수",
            "포트 번호",
        ],
        "answer": 0,
        "explanation": "UNION은 양쪽 SELECT의 컬럼 수가 같아야 한다.",
    },
    {
        "id": "sq-06",
        "question": "SQL 주석 `--` 또는 `#`의 공격적 활용은?",
        "options": [
            "주석으로 성능 향상",
            "쿼리 뒷부분(LIMIT, 추가 조건 등)을 무효화",
            "쿠키 삭제",
            "로그 숨김",
        ],
        "answer": 1,
        "explanation": "주석으로 쿼리 나머지를 잘라 원하는 형태로 만든다.",
    },
    {
        "id": "sq-07",
        "question": "DVWA SQLi Low 단계 쿼리의 특징은?",
        "options": [
            "숫자 검증",
            "파라미터 바인딩",
            "문자열 컨텍스트 `'$id'`, 필터 없음",
            "토큰 검사",
        ],
        "answer": 2,
        "explanation": "Low는 따옴표 문자열에 입력을 그대로 결합한다.",
    },
    {
        "id": "sq-08",
        "question": "DVWA SQLi Low에서 전체 비밀번호 해시를 덤프하는 입력은?",
        "options": [
            "`; DROP TABLE users`",
            "`1`",
            "`admin`",
            "`' UNION SELECT user, password FROM users -- `",
        ],
        "answer": 3,
        "explanation": "UNION으로 user/password 컬럼을 끌어와 덤프한다.",
    },
    {
        "id": "sq-09",
        "question": "DVWA SQLi Medium 단계의 입력 방식/컨텍스트는?",
        "options": [
            "드롭다운 + 숫자 컨텍스트(`= $id`)",
            "자유 텍스트 문자열",
            "파일 업로드",
            "쿠키",
        ],
        "answer": 0,
        "explanation": "Medium은 드롭다운으로 보내고 숫자 컨텍스트라 따옴표가 필요 없다.",
    },
    {
        "id": "sq-10",
        "question": "Medium 단계를 공략하려면 무엇이 필요한가?",
        "options": [
            "쿠키 삭제",
            "요청 변조(DevTools/Burp)로 id 값을 주입 payload로 교체",
            "서버 재시작",
            "CSS 수정",
        ],
        "answer": 1,
        "explanation": "드롭다운이라 화면에선 1~5만 가므로 요청을 가로채 변조해야 한다.",
    },
    {
        "id": "sq-11",
        "question": "숫자 컨텍스트 SQLi에서 따옴표가 필요 없는 이유는?",
        "options": [
            "서버가 변환해서",
            "DB가 숫자를 싫어해서",
            "쿼리가 `= $id` 형태라 문자열 경계가 없기 때문",
            "쿠키 때문",
        ],
        "answer": 2,
        "explanation": "따옴표로 감싸지 않으므로 `0 OR 1=1` 같이 바로 주입할 수 있다.",
    },
    {
        "id": "sq-12",
        "question": "DVWA SQLi High 단계에서 LIMIT 1을 우회하는 방법은?",
        "options": [
            "UNION 금지",
            "쿠키 변조",
            "서버 종료",
            "주석(--)으로 LIMIT 절을 제거",
        ],
        "answer": 3,
        "explanation": "`' UNION SELECT ... -- `로 뒤의 LIMIT 1을 주석 처리한다.",
    },
    {
        "id": "sq-13",
        "question": "DVWA SQLi Impossible 단계의 방어는?",
        "options": [
            "is_numeric 검증 + 파라미터 바인딩(Prepared Statement)",
            "블랙리스트",
            "길이 제한만",
            "쿠키 암호화",
        ],
        "answer": 0,
        "explanation": "입력을 숫자로 검증하고 바인딩으로 구조와 분리한다.",
    },
    {
        "id": "sq-14",
        "question": "SQLi의 근본 방어로 가장 올바른 것은?",
        "options": [
            "작은따옴표를 두 개로 치환",
            "파라미터 바인딩(Prepared Statement)",
            "입력 길이 제한",
            "WAF만",
        ],
        "answer": 1,
        "explanation": "바인딩은 입력을 값으로만 다뤄 구조 변경을 원천 차단한다.",
    },
    {
        "id": "sq-15",
        "question": "파라미터 바인딩이 SQLi를 막는 원리는?",
        "options": [
            "쿼리를 캐시",
            "입력을 삭제",
            "입력을 쿼리 구조와 분리해 순수 데이터로 전달",
            "서버를 분리",
        ],
        "answer": 2,
        "explanation": "플레이스홀더(?)에 값만 바인딩되어 구조가 바뀌지 않는다.",
    },
    {
        "id": "sq-16",
        "question": "다음 중 SQLi 방어로 '불완전한' 것은?",
        "options": [
            "저장 프로시저(안전 사용 시)",
            "파라미터 바인딩",
            "ORM의 파라미터화 쿼리",
            "특수문자 블랙리스트 필터",
        ],
        "answer": 3,
        "explanation": "블랙리스트는 우회 가능해 단독으로는 불완전하다.",
    },
    {
        "id": "sq-17",
        "question": "Error-based SQLi의 특징은?",
        "options": [
            "DB 오류 메시지로 정보를 유추",
            "응답 지연으로 추론",
            "참/거짓만으로 추론",
            "브라우저에서 실행",
        ],
        "answer": 0,
        "explanation": "상세 오류 메시지가 노출되면 구조·데이터를 역추론할 수 있다.",
    },
    {
        "id": "sq-18",
        "question": "상세 오류 메시지 노출을 줄이는 운영 방어는?",
        "options": [
            "오류를 그대로 노출",
            "사용자에겐 일반화된 오류, 상세는 서버 로그로만",
            "오류 비활성화 불가",
            "쿠키에 기록",
        ],
        "answer": 1,
        "explanation": "정보 노출을 줄이려면 사용자에게 상세 오류를 주지 않는다.",
    },
    {
        "id": "sq-19",
        "question": "Stacked Queries(스택 쿼리)란?",
        "options": [
            "쿠키 누적",
            "UNION의 다른 이름",
            "`;`로 여러 구문을 한 번에 실행(지원 드라이버 한정)",
            "로그 누적",
        ],
        "answer": 2,
        "explanation": "세미콜론으로 추가 구문 실행을 시도하지만 드라이버/설정에 따라 차단된다.",
    },
    {
        "id": "sq-20",
        "question": "최소 권한 DB 계정 사용이 SQLi 피해를 줄이는 이유는?",
        "options": [
            "쿠키를 보호함",
            "주입을 차단함",
            "쿼리를 빠르게 함",
            "주입 성공 시에도 가능한 작업 범위가 제한됨",
        ],
        "answer": 3,
        "explanation": "권한이 작으면 DROP/파일접근 등 피해 확대를 줄인다(심층 방어).",
    },
    {
        "id": "sq-21",
        "question": "`mysqli_real_escape_string` 같은 이스케이프만으로 부족한 이유는?",
        "options": [
            "숫자 컨텍스트 등에서 우회 가능하고 바인딩이 더 안전",
            "항상 실패해서",
            "느려서",
            "DB를 깨서",
        ],
        "answer": 0,
        "explanation": "이스케이프는 상황 의존적이라 바인딩이 권장된다.",
    },
    {
        "id": "sq-22",
        "question": "DVWA SQLi에서 성공을 증명하는 전형적 결과는?",
        "options": [
            "서버 종료",
            "users 테이블의 로그인/비밀번호 해시가 화면에 나타남",
            "이미지 변경",
            "쿠키 증가",
        ],
        "answer": 1,
        "explanation": "정상 조회로 안 나오는 password 컬럼이 노출되면 성공이다.",
    },
    {
        "id": "sq-23",
        "question": "SQLi 점검 시 가장 기초적인 신호는?",
        "options": [
            "CPU 온도",
            "디스크 용량",
            "작은따옴표 입력 시 쿼리 오류/동작 변화",
            "DNS TTL",
        ],
        "answer": 2,
        "explanation": "`'` 입력으로 오류나 결과 변화가 나타나면 주입 가능성이 있다.",
    },
    {
        "id": "sq-24",
        "question": "ORM 사용이 SQLi에 유리한 이유는?",
        "options": [
            "쿠키를 암호화",
            "쿼리를 숨김",
            "서버를 분리",
            "기본적으로 파라미터화 쿼리를 생성",
        ],
        "answer": 3,
        "explanation": "ORM은 보통 바인딩을 사용하지만 raw 쿼리 결합 시엔 여전히 위험하다.",
    },
    {
        "id": "sq-25",
        "question": "다음 중 SQLi 벡터가 될 수 있는 입력이 아닌 것은?",
        "options": [
            "서버 내부 상수",
            "쿠키 값",
            "HTTP 헤더",
            "검색어, 로그인 폼, 정렬 파라미터",
        ],
        "answer": 0,
        "explanation": "사용자 제어가 아닌 내부 상수는 벡터가 아니다.",
    },
    {
        "id": "sq-26",
        "question": "정렬(ORDER BY) 파라미터 주입이 특히 까다로운 이유는?",
        "options": [
            "항상 안전",
            "컬럼명 위치라 바인딩이 어려워 화이트리스트가 필요",
            "숫자만 와서",
            "쿠키라서",
        ],
        "answer": 1,
        "explanation": "ORDER BY 컬럼은 값이 아니라 식별자라 허용 목록 검증이 필요하다.",
    },
    {
        "id": "sq-27",
        "question": "`UNION SELECT NULL, NULL` 로 먼저 시도하는 이유는?",
        "options": [
            "쿠키 확인",
            "서버를 느리게",
            "컬럼 개수와 타입 호환을 탐색하기 위해",
            "로그 삭제",
        ],
        "answer": 2,
        "explanation": "NULL로 컬럼 수/타입을 맞춰 가며 UNION 가능 형태를 찾는다.",
    },
    {
        "id": "sq-28",
        "question": "SQLi로 인한 '데이터 유출' 외의 위험은?",
        "options": [
            "폰트 변경",
            "CSS 깨짐",
            "이미지 손상",
            "데이터 변조·삭제, 권한 상승, 경우에 따라 RCE",
        ],
        "answer": 3,
        "explanation": "환경에 따라 변조/삭제/파일접근/명령실행까지 확대될 수 있다.",
    },
    {
        "id": "sq-29",
        "question": "다음 중 SQLi 방어로 가장 권장되는 코드 패턴은?",
        "options": [
            "`cursor.execute('... WHERE id = ?', [id])`",
            "`'... WHERE id = ' + id`",
            "`f\"... id = {id}\"`",
            "`'... id = %s' % id`",
        ],
        "answer": 0,
        "explanation": "플레이스홀더에 값을 바인딩하는 패턴이 안전하다.",
    },
    {
        "id": "sq-30",
        "question": "로그인 폼 SQLi(`' OR '1'='1' -- `)가 성공하면?",
        "options": [
            "서버 재시작",
            "비밀번호 없이 인증 우회 가능",
            "쿠키 삭제",
            "CSS 변경",
        ],
        "answer": 1,
        "explanation": "조건이 참이 되어 자격 검증을 우회한다.",
    },
    {
        "id": "sq-31",
        "question": "Prepared Statement에서 플레이스홀더에 들어가지 못하는 것은?",
        "options": [
            "숫자 값",
            "문자열 값",
            "테이블명/컬럼명 같은 식별자",
            "날짜 값",
        ],
        "answer": 2,
        "explanation": "식별자는 바인딩 대상이 아니므로 화이트리스트로 처리한다.",
    },
    {
        "id": "sq-32",
        "question": "SQLi 탐지용 WAF 규칙만 믿기 어려운 이유는?",
        "options": [
            "쿠키 때문",
            "WAF가 느려서",
            "WAF가 DB를 깨서",
            "인코딩/주석/대소문자 변형으로 우회 가능",
        ],
        "answer": 3,
        "explanation": "WAF는 보조이며 바인딩이 근본이다.",
    },
    {
        "id": "sq-33",
        "question": "다음 중 '안전 단계(Impossible)'가 어떤 입력도 막는 이유는?",
        "options": [
            "숫자 검증 + 바인딩으로 구조 변경 자체가 불가",
            "서버가 느려서",
            "쿠키 때문",
            "WAF 때문",
        ],
        "answer": 0,
        "explanation": "값만 바인딩되어 주입 구문이 구조에 영향을 못 준다.",
    },
    {
        "id": "sq-34",
        "question": "SQLi와 Command Injection의 공통 교훈은?",
        "options": [
            "둘 다 브라우저 취약점",
            "신뢰 못 할 입력을 명령/쿼리 구조에 직접 결합하지 말 것",
            "둘 다 CSS 문제",
            "둘 다 쿠키 문제",
        ],
        "answer": 1,
        "explanation": "입력을 구조와 분리(바인딩/인자배열)하는 것이 공통 방어다.",
    },
    {
        "id": "sq-35",
        "question": "Second-order SQLi(2차 주입)란?",
        "options": [
            "클라이언트 주입",
            "즉시 주입",
            "저장된 값이 나중에 다른 쿼리에서 주입으로 작동",
            "쿠키 주입",
        ],
        "answer": 2,
        "explanation": "입력이 저장되었다가 이후 쿼리에 결합될 때 발생한다.",
    },
    {
        "id": "sq-36",
        "question": "다음 중 SQLi 완화에 직접 기여하지 않는 것은?",
        "options": [
            "오류 메시지 일반화",
            "파라미터 바인딩",
            "최소 권한 계정",
            "이미지 썸네일 캐시",
        ],
        "answer": 3,
        "explanation": "썸네일 캐시는 성능 요소로 SQLi와 무관하다.",
    },
    {
        "id": "sq-37",
        "question": "`LIKE` 검색에 사용자 값을 넣을 때 주의점은?",
        "options": [
            "바인딩 사용 + 와일드카드(%,_) 이스케이프 고려",
            "그냥 결합",
            "검증 생략",
            "eval 사용",
        ],
        "answer": 0,
        "explanation": "LIKE도 바인딩하고 와일드카드 처리를 고려해야 한다.",
    },
    {
        "id": "sq-38",
        "question": "DVWA SQLi에서 admin의 비밀번호 해시가 '정상 조회로는' 안 보이는 이유는?",
        "options": [
            "DB가 숨겨서",
            "정상 쿼리는 first_name/last_name만 선택하기 때문",
            "쿠키 때문",
            "HTTPS 때문",
        ],
        "answer": 1,
        "explanation": "password 컬럼은 UNION 주입으로만 끌어올 수 있다.",
    },
    {
        "id": "sq-39",
        "question": "SQLi 방어에서 '입력 검증'의 위치는?",
        "options": [
            "불필요",
            "유일한 방어",
            "보조 방어(형식/범위)이며 바인딩과 병행",
            "성능 전용",
        ],
        "answer": 2,
        "explanation": "검증은 보조이고 바인딩이 핵심이다.",
    },
    {
        "id": "sq-40",
        "question": "sqlmap 같은 자동화 도구가 겨냥하는 것은?",
        "options": [
            "DNS 조회",
            "이미지 최적화",
            "CSS 린트",
            "주입 지점 탐지·데이터 자동 추출",
        ],
        "answer": 3,
        "explanation": "sqlmap은 SQLi를 자동 탐지/익스플로잇한다.",
    },
    {
        "id": "sq-41",
        "question": "다음 중 '컨텍스트'가 SQLi 공략에 중요한 이유는?",
        "options": [
            "문자열/숫자 컨텍스트에 따라 필요한 주입 형태가 다름",
            "속도 때문",
            "쿠키 때문",
            "CSS 때문",
        ],
        "answer": 0,
        "explanation": "따옴표 유무 등 컨텍스트에 맞춰 payload를 구성해야 한다.",
    },
    {
        "id": "sq-42",
        "question": "SQLi로 유출된 비밀번호가 'MD5 해시'일 때의 위험은?",
        "options": [
            "항상 안전",
            "레인보우 테이블/크래킹으로 평문 복원 위험",
            "복원 불가",
            "서버 종료",
        ],
        "answer": 1,
        "explanation": "MD5는 약해 해시도 크래킹 위험이 크다(강한 해시 필요).",
    },
    {
        "id": "sq-43",
        "question": "SQLi 수정 후 재검증 시 확인할 점은?",
        "options": [
            "CPU만",
            "새 기능만",
            "모든 주입 지점이 바인딩으로 전환됐는지",
            "쿠키만",
        ],
        "answer": 2,
        "explanation": "누락된 raw 쿼리 결합이 없는지 전수 확인해야 한다.",
    },
    {
        "id": "sq-44",
        "question": "다음 중 SQLi와 가장 거리가 먼 방어는?",
        "options": [
            "오류 일반화",
            "파라미터 바인딩",
            "최소 권한",
            "이미지 매직바이트 검사",
        ],
        "answer": 3,
        "explanation": "매직바이트 검사는 파일 업로드 방어다.",
    },
    {
        "id": "sq-45",
        "question": "ORM에서도 SQLi가 생길 수 있는 경우는?",
        "options": [
            "raw SQL에 문자열 결합으로 입력을 넣을 때",
            "항상 안전",
            "숫자만 쓸 때",
            "쿠키 쓸 때",
        ],
        "answer": 0,
        "explanation": "ORM이라도 raw 쿼리에 결합하면 주입이 가능하다.",
    },
    {
        "id": "sq-46",
        "question": "`information_schema`가 공격자에게 유용한 이유는?",
        "options": [
            "성능 향상",
            "테이블/컬럼 구조를 조회해 공격 대상을 파악",
            "쿠키 저장",
            "로그 삭제",
        ],
        "answer": 1,
        "explanation": "스키마 메타데이터로 테이블·컬럼명을 알아낸다.",
    },
    {
        "id": "sq-47",
        "question": "SQLi 방어로 '뷰/저장 프로시저'가 만능이 아닌 이유는?",
        "options": [
            "느려서",
            "항상 안전",
            "내부에서 동적 SQL을 문자열 결합하면 여전히 취약",
            "쿠키 때문",
        ],
        "answer": 2,
        "explanation": "프로시저 내부에서 동적 결합을 하면 주입 위험이 남는다.",
    },
    {
        "id": "sq-48",
        "question": "다음 중 SQLi 성공 가능성을 '낮추는' 설계는?",
        "options": [
            "오류 상세 노출",
            "모든 입력을 문자열 결합",
            "검증 생략",
            "모든 쿼리를 파라미터화, 식별자는 화이트리스트",
        ],
        "answer": 3,
        "explanation": "파라미터화 + 식별자 화이트리스트가 바람직하다.",
    },
    {
        "id": "sq-49",
        "question": "SQLi 종합 방어로 가장 올바른 조합은?",
        "options": [
            "파라미터 바인딩 + 최소 권한 + 오류 일반화 + 입력 검증",
            "WAF만",
            "HTTPS만",
            "길이 제한만",
        ],
        "answer": 0,
        "explanation": "바인딩을 핵심으로 권한·오류·검증을 병행하는 심층 방어.",
    },
    {
        "id": "sq-50",
        "question": "SQL Injection을 한 문장으로 요약하면?",
        "options": [
            "브라우저 스크립트 실행 문제",
            "입력이 쿼리 구조를 바꿀 수 있을 때 발생하며 바인딩으로 막는다",
            "파일 실행 문제",
            "쿠키 위조 문제",
        ],
        "answer": 1,
        "explanation": "데이터/명령 분리(바인딩)가 핵심 방어다.",
    },
]
