"""XSS (Stored) 미션 퀴즈 문항 은행 (50문항)."""

QUESTIONS = [
    {
        "id": "xs-01",
        "question": "Stored(저장형) XSS의 정의는?",
        "options": [
            "입력이 저장되었다가 조회하는 모든 사용자에게 실행되는 XSS",
            "요청 응답에 1회성 반사되는 XSS",
            "DOM 조작으로만 발생",
            "SQL 주입의 일종",
        ],
        "answer": 0,
        "explanation": "저장형 XSS는 악성 입력이 서버/DB에 저장되어 열람하는 사용자마다 실행된다.",
    },
    {
        "id": "xs-02",
        "question": "Stored XSS가 Reflected보다 위험한 이유는?",
        "options": [
            "항상 관리자만 노출",
            "피해자 클릭 없이 열람만으로 다수에게 반복 실행",
            "자바스크립트가 필요 없어서",
            "서버를 파괴해서",
        ],
        "answer": 1,
        "explanation": "한 번 저장되면 게시물을 보는 모든 사용자에게 지속적으로 실행된다.",
    },
    {
        "id": "xs-03",
        "question": "Stored XSS의 또 다른 이름은?",
        "options": [
            "Blind XSS만",
            "Reflected XSS",
            "Persistent XSS(지속형)",
            "CSRF",
        ],
        "answer": 2,
        "explanation": "저장되어 지속 실행되므로 Persistent XSS라고도 한다.",
    },
    {
        "id": "xs-04",
        "question": "Stored XSS의 전형적 발생 지점은?",
        "options": [
            "DNS 레코드",
            "정적 이미지",
            "서버 상수",
            "게시판·댓글·방명록·프로필 등 저장되는 입력",
        ],
        "answer": 3,
        "explanation": "사용자 입력이 저장되고 다시 표시되는 기능이 저장형 XSS의 온상이다.",
    },
    {
        "id": "xs-05",
        "question": "DVWA Stored XSS(Guestbook)의 입력 필드는?",
        "options": [
            "Name과 Message",
            "User ID만",
            "IP 주소만",
            "파일만",
        ],
        "answer": 0,
        "explanation": "DVWA 방명록은 Name과 Message 두 필드를 받는다.",
    },
    {
        "id": "xs-06",
        "question": "DVWA Stored Low 단계의 취약 벡터로 흔한 것은?",
        "options": [
            "CSRF 토큰",
            "Message 필드",
            "세션 쿠키",
            "User-Agent",
        ],
        "answer": 1,
        "explanation": "Low는 필터가 약해 Message에 스크립트를 넣어 저장·실행할 수 있다.",
    },
    {
        "id": "xs-07",
        "question": "DVWA Stored Medium 단계의 특징은?",
        "options": [
            "입력 차단",
            "모든 필드 인코딩",
            "Message는 안전 처리되고 Name 필터가 '<script>'만 제거",
            "숫자만 허용",
        ],
        "answer": 2,
        "explanation": "Medium은 Message를 strip_tags/인코딩하지만 Name은 <script>만 제거해 Name이 벡터가 된다.",
    },
    {
        "id": "xs-08",
        "question": "Medium 단계에서 Name 필드를 뚫는 대표 페이로드는?",
        "options": [
            "`; cat /etc/passwd`",
            "`<script>alert(1)</script>`",
            "`' OR '1'='1`",
            "`<img src=x onerror=alert(1)>`",
        ],
        "answer": 3,
        "explanation": "script 문자열만 제거하므로 다른 태그의 이벤트 핸들러로 우회한다.",
    },
    {
        "id": "xs-09",
        "question": "DVWA Stored High 단계의 Name 필터는?",
        "options": [
            "정규식으로 script 류 태그 제거",
            "완전 차단",
            "숫자만 허용",
            "필터 없음",
        ],
        "answer": 0,
        "explanation": "High는 preg_replace로 script 형태를 제거하지만 img 등은 통과된다.",
    },
    {
        "id": "xs-10",
        "question": "High 단계 Name 필드 우회 페이로드로 적절한 것은?",
        "options": [
            "`<script>...`",
            "`<img src=x onerror=alert(1)>`",
            "SQL UNION",
            "파일 업로드",
        ],
        "answer": 1,
        "explanation": "script류만 막으므로 img 이벤트 핸들러로 우회한다.",
    },
    {
        "id": "xs-11",
        "question": "DVWA Stored Impossible 단계의 방어는?",
        "options": [
            "쿠키 암호화",
            "입력 길이만 제한",
            "Name·Message 모두 출력 인코딩/새니타이즈",
            "필터 없음",
        ],
        "answer": 2,
        "explanation": "모든 필드를 htmlspecialchars 등으로 인코딩해 실행을 차단한다.",
    },
    {
        "id": "xs-12",
        "question": "저장형 XSS 방어로 'strip_tags'만 믿으면 안 되는 이유는?",
        "options": [
            "쿠키를 지워서",
            "느려서",
            "DB를 깨서",
            "불완전해 우회 가능하고 출력 인코딩이 병행돼야 함",
        ],
        "answer": 3,
        "explanation": "태그 제거는 불완전하므로 출력 시 인코딩/새니타이즈가 필요하다.",
    },
    {
        "id": "xs-13",
        "question": "저장형 XSS에서 '저장 시점 방어'와 '출력 시점 방어' 중 권장되는 것은?",
        "options": [
            "출력 시점 인코딩(또는 둘 다)",
            "저장 시점만",
            "둘 다 불필요",
            "클라이언트 차단만",
        ],
        "answer": 0,
        "explanation": "출력 컨텍스트에서 인코딩하는 것이 핵심이며, 입력 검증과 병행하면 더 안전하다.",
    },
    {
        "id": "xs-14",
        "question": "관리자 페이지에서 저장형 XSS가 특히 위험한 이유는?",
        "options": [
            "속도가 느려서",
            "관리자 세션/권한 탈취로 이어질 수 있어서",
            "CSS가 깨져서",
            "로그가 많아서",
        ],
        "answer": 1,
        "explanation": "관리자가 악성 글을 열람하면 높은 권한의 세션이 탈취될 수 있다.",
    },
    {
        "id": "xs-15",
        "question": "저장형 XSS의 '지속성(persistence)'이 의미하는 것은?",
        "options": [
            "서버 재시작 시 사라짐",
            "1회만 실행",
            "한 번 저장되면 삭제 전까지 계속 실행",
            "브라우저마다 다름",
        ],
        "answer": 2,
        "explanation": "저장된 페이로드는 제거되기 전까지 열람할 때마다 실행된다.",
    },
    {
        "id": "xs-16",
        "question": "Blind XSS는 저장형 XSS와 어떤 관계인가?",
        "options": [
            "CSRF의 변형",
            "Reflected의 일종",
            "DOM XSS와 동일",
            "결과가 즉시 안 보이고 다른 사용자(관리자) 화면에서 터지는 저장형의 변형",
        ],
        "answer": 3,
        "explanation": "Blind XSS는 공격자가 결과를 직접 못 보지만 백오피스 등에서 실행되는 저장형 변형이다.",
    },
    {
        "id": "xs-17",
        "question": "저장형 XSS 방어에 가장 적절한 라이브러리 접근은?",
        "options": [
            "DOMPurify 등 화이트리스트 새니타이저",
            "블랙리스트 키워드 제거",
            "정규식으로 script만 제거",
            "입력 대문자화",
        ],
        "answer": 0,
        "explanation": "허용 목록 기반 새니타이저가 저장형 XSS에 효과적이다.",
    },
    {
        "id": "xs-18",
        "question": "`<svg/onload=alert(1)>` 류가 저장형에서 주는 교훈은?",
        "options": [
            "svg는 안전",
            "script 외 태그·이벤트도 저장되어 실행될 수 있다",
            "이미지엔 코드 없음",
            "인코딩 불필요",
        ],
        "answer": 1,
        "explanation": "다양한 태그/이벤트가 저장되어 실행 벡터가 될 수 있다.",
    },
    {
        "id": "xs-19",
        "question": "저장형 XSS 점검 시 확인할 핵심은?",
        "options": [
            "CPU 온도",
            "디스크 용량",
            "저장된 입력이 다른 화면에서 인코딩 없이 렌더링되는지",
            "DNS TTL",
        ],
        "answer": 2,
        "explanation": "저장값이 출력될 때 인코딩되는지가 핵심 점검 포인트다.",
    },
    {
        "id": "xs-20",
        "question": "HttpOnly 쿠키가 저장형 XSS 피해를 줄이는 방식은?",
        "options": [
            "CSRF 차단",
            "쿠키 암호화",
            "XSS 자체 차단",
            "스크립트의 쿠키 접근 차단으로 세션 탈취 완화",
        ],
        "answer": 3,
        "explanation": "HttpOnly는 document.cookie 접근을 막아 세션 탈취를 완화한다(근본 방어는 인코딩).",
    },
    {
        "id": "xs-21",
        "question": "저장형 XSS에서 '피해 범위'가 넓은 이유는?",
        "options": [
            "게시물을 보는 모든 사용자에게 실행되므로",
            "서버만 영향받아서",
            "1명만 영향받아서",
            "HTTPS 때문",
        ],
        "answer": 0,
        "explanation": "저장된 콘텐츠를 열람하는 다수 사용자 모두가 피해 대상이 된다.",
    },
    {
        "id": "xs-22",
        "question": "댓글 기능에 저장형 XSS가 있을 때 올바른 수정은?",
        "options": [
            "댓글 길이만 제한",
            "출력 시 HTML 인코딩 또는 새니타이즈 적용",
            "댓글 수 제한",
            "쿠키 삭제",
        ],
        "answer": 1,
        "explanation": "출력 인코딩/새니타이즈가 근본 수정이다.",
    },
    {
        "id": "xs-23",
        "question": "리치 텍스트(서식 허용) 게시물에서 XSS를 막는 현실적 방법은?",
        "options": [
            "인코딩 생략",
            "모든 태그 허용",
            "허용 태그/속성만 남기는 새니타이저 적용",
            "클라이언트 검증만",
        ],
        "answer": 2,
        "explanation": "서식이 필요하면 화이트리스트 기반 새니타이저로 안전 태그만 허용한다.",
    },
    {
        "id": "xs-24",
        "question": "다음 중 저장형 XSS와 가장 거리가 먼 방어는?",
        "options": [
            "CSP",
            "출력 인코딩",
            "새니타이저",
            "ping 입력 화이트리스트(숫자 옥텟) 검증",
        ],
        "answer": 3,
        "explanation": "ping 옥텟 검증은 Command Injection 방어로 저장형 XSS와 무관하다.",
    },
    {
        "id": "xs-25",
        "question": "저장형 XSS에서 '저장은 되지만 실행은 안 되게' 하려면?",
        "options": [
            "출력 시 태그를 엔티티로 인코딩",
            "저장을 막음",
            "서버 재시작",
            "쿠키 삭제",
        ],
        "answer": 0,
        "explanation": "출력 인코딩하면 저장값이 글자로만 보여 실행되지 않는다.",
    },
    {
        "id": "xs-26",
        "question": "프로필 이름(Name) 필드가 XSS 벡터가 되는 전형적 상황은?",
        "options": [
            "이름이 숫자일 때",
            "이름이 여러 페이지에 인코딩 없이 노출될 때",
            "이름이 암호화될 때",
            "이름이 비어있을 때",
        ],
        "answer": 1,
        "explanation": "저장된 이름이 여러 화면에 그대로 출력되면 저장형 XSS가 된다.",
    },
    {
        "id": "xs-27",
        "question": "저장형 XSS와 CSRF를 결합한 공격의 효과는?",
        "options": [
            "DB 백업",
            "서버 성능 향상",
            "XSS로 토큰을 읽어 CSRF 방어를 무력화할 수 있음",
            "무관함",
        ],
        "answer": 2,
        "explanation": "XSS로 CSRF 토큰을 탈취하면 토큰 기반 방어도 뚫을 수 있다.",
    },
    {
        "id": "xs-28",
        "question": "다음 중 저장형 XSS 성공의 직접 신호는?",
        "options": [
            "CPU 사용률",
            "HTTP 201",
            "DB 크기 증가",
            "저장된 글을 열람할 때 스크립트가 실행됨",
        ],
        "answer": 3,
        "explanation": "열람 시 스크립트 실행이 저장형 성립의 증거다.",
    },
    {
        "id": "xs-29",
        "question": "출력 인코딩을 '모든 출력 지점'에 적용해야 하는 이유는?",
        "options": [
            "한 곳이라도 누락되면 저장값이 실행될 수 있어서",
            "속도 때문",
            "DB 때문",
            "쿠키 때문",
        ],
        "answer": 0,
        "explanation": "저장값은 여러 화면에 쓰이므로 모든 출력 지점에서 인코딩이 필요하다.",
    },
    {
        "id": "xs-30",
        "question": "저장형 XSS에서 WAF만으로 안심할 수 없는 이유는?",
        "options": [
            "WAF가 느려서",
            "인코딩 변형·다양한 태그로 우회 가능하므로 근본 방어가 필요",
            "WAF가 DB를 깨서",
            "WAF가 쿠키를 지워서",
        ],
        "answer": 1,
        "explanation": "WAF는 보조 수단이며 출력 인코딩/새니타이즈가 근본 방어다.",
    },
    {
        "id": "xs-31",
        "question": "Markdown 렌더링 기능에서 XSS를 막으려면?",
        "options": [
            "검증 생략",
            "원본을 그대로 innerHTML",
            "렌더링 결과 HTML을 새니타이즈",
            "eval 사용",
        ],
        "answer": 2,
        "explanation": "Markdown→HTML 변환 후 결과를 새니타이즈해야 안전하다.",
    },
    {
        "id": "xs-32",
        "question": "저장형 XSS 수정 후 '재검증' 시 확인할 점은?",
        "options": [
            "쿠키만 확인",
            "새 글만 확인",
            "CPU만 확인",
            "기존 저장된 악성 데이터도 출력 시 무력화되는지",
        ],
        "answer": 3,
        "explanation": "이미 저장된 페이로드도 출력 인코딩으로 무력화되는지 확인해야 한다.",
    },
    {
        "id": "xs-33",
        "question": "저장형 XSS 방어에서 '입력 검증'의 역할은?",
        "options": [
            "보조 방어(형식 제한)이며 출력 인코딩과 병행",
            "유일한 방어",
            "불필요",
            "성능 최적화",
        ],
        "answer": 0,
        "explanation": "입력 검증은 보조이고 출력 인코딩이 핵심이다.",
    },
    {
        "id": "xs-34",
        "question": "다음 중 저장형 XSS 페이로드가 '실행되지 않도록' 만드는 출력은?",
        "options": [
            "`<img src=x onerror=alert(1)>` 로 표시",
            "`&lt;img src=x onerror=alert(1)&gt;` 로 표시",
            "innerHTML 삽입",
            "v-html 삽입",
        ],
        "answer": 1,
        "explanation": "엔티티로 인코딩되어 표시되면 태그가 생성되지 않아 실행되지 않는다.",
    },
    {
        "id": "xs-35",
        "question": "저장형 XSS와 가장 관련 깊은 공통 근본 원인은?",
        "options": [
            "큰 이미지",
            "느린 쿼리",
            "신뢰할 수 없는 데이터를 인코딩 없이 HTML로 출력",
            "긴 URL",
        ],
        "answer": 2,
        "explanation": "미인코딩 출력이 모든 XSS의 공통 근본 원인이다.",
    },
    {
        "id": "xs-36",
        "question": "다음 중 저장형 XSS 완화에 직접 기여하지 않는 것은?",
        "options": [
            "새니타이저",
            "출력 인코딩",
            "CSP",
            "DB 샤딩",
        ],
        "answer": 3,
        "explanation": "DB 샤딩은 확장성 기법으로 XSS와 무관하다.",
    },
    {
        "id": "xs-37",
        "question": "저장형 XSS에서 이메일 알림 템플릿도 점검해야 하는 이유는?",
        "options": [
            "저장값이 메일(HTML)에도 인코딩 없이 들어가면 실행/피싱 위험",
            "메일이 느려서",
            "DB 때문",
            "무관함",
        ],
        "answer": 0,
        "explanation": "저장값이 여러 출력 채널(메일 등)로 나가므로 모두 점검해야 한다.",
    },
    {
        "id": "xs-38",
        "question": "저장형 XSS에서 '다단계 피해'의 예는?",
        "options": [
            "서버 종료",
            "피해자 브라우저에서 추가 글을 작성해 전파(웜)",
            "DNS 변경",
            "디스크 암호화",
        ],
        "answer": 1,
        "explanation": "XSS 웜처럼 피해자가 다시 페이로드를 퍼뜨릴 수 있다.",
    },
    {
        "id": "xs-39",
        "question": "저장형 XSS 방어 설계의 올바른 순서 개념은?",
        "options": [
            "클라이언트만 검증",
            "출력 인코딩 생략",
            "입력 검증(보조) → 저장 → 출력 인코딩(핵심)",
            "인코딩 불필요",
        ],
        "answer": 2,
        "explanation": "저장은 그대로 두더라도 출력 인코딩으로 안전하게 표시하는 것이 핵심이다.",
    },
    {
        "id": "xs-40",
        "question": "DVWA Stored에서 Message가 안전해도 Name으로 공격 가능한 이유는?",
        "options": [
            "DB 때문",
            "서버가 느려서",
            "쿠키 때문",
            "필드마다 적용된 방어 수준이 달라서",
        ],
        "answer": 3,
        "explanation": "Medium/High에서 Message는 인코딩하지만 Name은 불완전 필터라 벡터가 된다.",
    },
    {
        "id": "xs-41",
        "question": "저장형 XSS에서 CSP의 역할은?",
        "options": [
            "인라인 스크립트 제한으로 피해 완화(심층 방어)",
            "입력 삭제",
            "DB 암호화",
            "SQLi 차단",
        ],
        "answer": 0,
        "explanation": "CSP는 저장형 XSS가 실행돼도 영향을 줄이는 보조 방어다.",
    },
    {
        "id": "xs-42",
        "question": "다음 중 저장형 XSS의 '탐지'를 어렵게 만드는 요인은?",
        "options": [
            "항상 즉시 보임",
            "즉시 반응이 없고 다른 사용자 화면에서 터지는 경우(Blind)",
            "서버 로그에 모두 남음",
            "HTTPS",
        ],
        "answer": 1,
        "explanation": "Blind 특성상 공격자/운영자가 즉시 알아채기 어렵다.",
    },
    {
        "id": "xs-43",
        "question": "저장형 XSS에서 사용자 아바타 URL을 받을 때 주의점은?",
        "options": [
            "검증 생략",
            "모든 URL 허용",
            "javascript:/data: 등 위험 스킴 차단 및 속성 인코딩",
            "eval 사용",
        ],
        "answer": 2,
        "explanation": "URL 속성에도 위험 스킴·따옴표 탈출이 가능하므로 검증·인코딩이 필요하다.",
    },
    {
        "id": "xs-44",
        "question": "저장형 XSS 방어로 '충분하지 않은' 것은?",
        "options": [
            "CSP",
            "서버 출력 인코딩",
            "새니타이저",
            "클라이언트에서만 태그 입력을 막음",
        ],
        "answer": 3,
        "explanation": "클라이언트 차단은 요청 변조로 우회되므로 서버 방어가 필요하다.",
    },
    {
        "id": "xs-45",
        "question": "저장형 XSS의 근본 수정 위치로 가장 적절한 것은?",
        "options": [
            "서버(또는 공통 템플릿)의 출력 인코딩/새니타이즈",
            "브라우저 설정",
            "방화벽",
            "DNS",
        ],
        "answer": 0,
        "explanation": "출력이 일어나는 서버/템플릿 레벨에서 공통으로 처리해야 한다.",
    },
    {
        "id": "xs-46",
        "question": "저장형 XSS와 Reflected XSS의 공통 방어는?",
        "options": [
            "SQL 바인딩",
            "출력 컨텍스트별 인코딩",
            "ping 옥텟 검증",
            "파일 매직바이트 검사",
        ],
        "answer": 1,
        "explanation": "두 XSS 모두 출력 인코딩이 공통 핵심 방어다.",
    },
    {
        "id": "xs-47",
        "question": "저장형 XSS 실습에서 '방명록 비우기'의 목적은?",
        "options": [
            "서버 재시작",
            "DB 삭제",
            "저장된 페이로드를 초기화해 재실습",
            "쿠키 초기화",
        ],
        "answer": 2,
        "explanation": "저장된 글을 비워 다음 시도를 깨끗이 시작하기 위함이다.",
    },
    {
        "id": "xs-48",
        "question": "다음 중 저장형 XSS 위험을 '높이는' 설계는?",
        "options": [
            "CSP 적용",
            "출력 인코딩 공통화",
            "새니타이저 적용",
            "사용자 입력을 여러 페이지에 인코딩 없이 공유 출력",
        ],
        "answer": 3,
        "explanation": "여러 출력 지점에 미인코딩 공유는 위험을 키운다.",
    },
    {
        "id": "xs-49",
        "question": "저장형 XSS 종합 방어로 가장 올바른 조합은?",
        "options": [
            "출력 인코딩/새니타이즈 + 입력 검증 + CSP/HttpOnly",
            "입력 길이 제한만",
            "HTTPS만",
            "클라이언트 차단만",
        ],
        "answer": 0,
        "explanation": "출력 인코딩을 핵심으로 입력 검증·CSP·쿠키 속성을 병행한다.",
    },
    {
        "id": "xs-50",
        "question": "저장형 XSS를 한 문장으로 요약하면?",
        "options": [
            "1회성 반사 XSS",
            "저장된 악성 입력이 열람자마다 실행되는 가장 지속적·광범위한 XSS",
            "클라이언트 전용 XSS",
            "SQL 주입",
        ],
        "answer": 1,
        "explanation": "저장·지속·다수 피해가 저장형 XSS의 핵심 특징이다.",
    },
]
