"""XSS (Reflected) 미션 퀴즈 문항 은행 (50문항)."""

QUESTIONS = [
    {
        "id": "xr-01",
        "question": "Reflected XSS의 정의로 가장 정확한 것은?",
        "options": [
            "요청 파라미터가 즉시 응답 HTML에 반사되어 스크립트가 실행되는 취약점",
            "입력이 서버 DB에 저장되었다가 실행되는 취약점",
            "브라우저 DOM 조작 과정에서만 발생하는 취약점",
            "SQL 쿼리에 악성 구문을 삽입하는 공격",
        ],
        "answer": 0,
        "explanation": "Reflected(반사형) XSS는 입력이 저장되지 않고 그 요청의 응답에 즉시 반사되어 실행된다.",
    },
    {
        "id": "xr-02",
        "question": "XSS에서 'Cross-Site Scripting'이 의미하는 핵심은?",
        "options": [
            "서버 간 요청 위조",
            "피해자 브라우저에서 공격자가 만든 스크립트가 실행됨",
            "교차 출처 리소스 공유 설정 오류",
            "DNS 캐시 오염",
        ],
        "answer": 1,
        "explanation": "XSS의 본질은 다른 사용자의 브라우저 컨텍스트에서 악성 스크립트가 실행되는 것이다.",
    },
    {
        "id": "xr-03",
        "question": "Reflected XSS가 Stored XSS와 다른 점은?",
        "options": [
            "서버에 영구 저장된다",
            "항상 관리자만 피해를 본다",
            "입력이 저장되지 않고 요청-응답 1회성으로 반사된다",
            "자바스크립트가 필요 없다",
        ],
        "answer": 2,
        "explanation": "Reflected는 저장되지 않으며 보통 악성 링크 클릭으로 1회 작동한다.",
    },
    {
        "id": "xr-04",
        "question": "Reflected XSS의 전형적인 공격 전달 방식은?",
        "options": [
            "쿠키 파일을 직접 복사",
            "데이터베이스에 직접 접속",
            "서버 셸에 명령 실행",
            "피해자가 악성 파라미터가 담긴 링크를 클릭하도록 유도",
        ],
        "answer": 3,
        "explanation": "공격자는 페이로드가 담긴 URL을 만들어 피해자가 클릭하게 유도한다.",
    },
    {
        "id": "xr-05",
        "question": "브라우저가 `<script>` 태그를 '글자'가 아니라 '실행할 코드'로 다루는 이유는?",
        "options": [
            "HTML 파서가 태그를 구조로 해석하기 때문",
            "서버가 강제로 실행하기 때문",
            "자바스크립트가 서버에서 실행되기 때문",
            "쿠키 때문",
        ],
        "answer": 0,
        "explanation": "브라우저 HTML 파서는 태그를 문서 구조로 해석하므로 script 태그를 코드로 실행한다.",
    },
    {
        "id": "xr-06",
        "question": "DVWA Reflected XSS Low 단계의 특징은?",
        "options": [
            "htmlspecialchars 적용",
            "입력을 아무 필터 없이 그대로 출력",
            "숫자만 허용",
            "CSP 강제",
        ],
        "answer": 1,
        "explanation": "Low는 필터가 없어 `<script>alert(1)</script>`가 바로 실행된다.",
    },
    {
        "id": "xr-07",
        "question": "DVWA Reflected XSS Medium 단계의 필터는?",
        "options": [
            "모든 태그 제거",
            "htmlspecialchars",
            "`<script>` 문자열을 치환(대소문자 구분)",
            "입력 길이 제한만",
        ],
        "answer": 2,
        "explanation": "Medium은 소문자 `<script>`만 제거하므로 대문자/다른 태그로 우회된다.",
    },
    {
        "id": "xr-08",
        "question": "Medium 단계(`<script>` 문자열 제거)를 우회하는 대표 방법은?",
        "options": [
            "HTTPS 사용",
            "URL 인코딩만 하면 됨",
            "쿠키 삭제",
            "`<SCRIPT>` 대문자 또는 `<img onerror>` 사용",
        ],
        "answer": 3,
        "explanation": "태그 이름은 대소문자를 구분하지 않고, script가 아닌 태그의 이벤트 속성으로도 실행 가능하다.",
    },
    {
        "id": "xr-09",
        "question": "`<img src=x onerror=alert(1)>` 가 동작하는 원리는?",
        "options": [
            "존재하지 않는 src로 로드 실패 시 onerror 핸들러 실행",
            "이미지가 정상 로드되어 실행",
            "img 태그는 항상 스크립트를 실행",
            "브라우저 버그",
        ],
        "answer": 0,
        "explanation": "잘못된 src로 로딩이 실패하면 onerror에 지정한 코드가 실행된다.",
    },
    {
        "id": "xr-10",
        "question": "DVWA Reflected XSS High 단계의 필터 방식은?",
        "options": [
            "htmlspecialchars",
            "정규식으로 s·c·r·i·p·t 패턴 태그 제거",
            "모든 `<`,`>` 제거",
            "필터 없음",
        ],
        "answer": 1,
        "explanation": "High는 정규식 `/<(.*)s(.*)c(.*)r(.*)i(.*)p(.*)t/i`로 script 형태를 제거한다.",
    },
    {
        "id": "xr-11",
        "question": "High 단계(script 정규식 제거)를 우회하는 방법은?",
        "options": [
            "script 태그를 더 길게 작성",
            "대문자만 사용",
            "`<img src=x onerror=alert(1)>` 등 script 없는 태그+이벤트",
            "주석 삽입",
        ],
        "answer": 2,
        "explanation": "필터가 'script' 단어에만 집중하므로 다른 태그의 이벤트 핸들러로 우회한다.",
    },
    {
        "id": "xr-12",
        "question": "DVWA Reflected XSS Impossible 단계의 방어는?",
        "options": [
            "입력 길이 제한",
            "쿠키 암호화",
            "script 태그 제거",
            "htmlspecialchars로 출력 인코딩",
        ],
        "answer": 3,
        "explanation": "htmlspecialchars로 `<`,`>`,`\"`,`'`,`&`를 엔티티로 바꿔 태그 생성을 막는다.",
    },
    {
        "id": "xr-13",
        "question": "출력 인코딩(이스케이프)이 XSS를 막는 원리는?",
        "options": [
            "특수문자를 엔티티로 바꿔 '태그'가 아닌 '글자'로 표시",
            "입력을 삭제한다",
            "서버를 재시작한다",
            "요청을 차단한다",
        ],
        "answer": 0,
        "explanation": "`<`→`&lt;`로 바뀌면 브라우저가 태그로 해석하지 않아 실행되지 않는다.",
    },
    {
        "id": "xr-14",
        "question": "`<` 를 HTML 엔티티로 올바르게 인코딩한 것은?",
        "options": [
            "&gt;",
            "&lt;",
            "&amp;",
            "&quot;",
        ],
        "answer": 1,
        "explanation": "`<`는 `&lt;`로 인코딩된다.",
    },
    {
        "id": "xr-15",
        "question": "XSS 방어로 가장 근본적인 접근은?",
        "options": [
            "위험 키워드 블랙리스트 제거",
            "입력을 모두 대문자로 변환",
            "출력 시점에 컨텍스트별 인코딩 적용",
            "쿠키 사용 금지",
        ],
        "answer": 2,
        "explanation": "블랙리스트는 우회되므로 출력 컨텍스트에 맞는 인코딩이 근본 방어다.",
    },
    {
        "id": "xr-16",
        "question": "블랙리스트 기반 XSS 필터의 근본적 한계는?",
        "options": [
            "속도가 느리다",
            "HTTPS와 충돌한다",
            "메모리를 많이 쓴다",
            "허용 목록에 없는 변형(대소문자·이벤트 속성 등)으로 항상 우회 가능",
        ],
        "answer": 3,
        "explanation": "금지 목록에 없는 형태는 통과하므로 블랙리스트는 완전하지 않다.",
    },
    {
        "id": "xr-17",
        "question": "CSP(Content-Security-Policy)의 XSS 방어 역할은?",
        "options": [
            "허용된 출처의 스크립트만 실행하도록 제한해 피해 완화",
            "입력을 자동 삭제",
            "쿠키를 암호화",
            "SQL 인젝션 차단",
        ],
        "answer": 0,
        "explanation": "CSP는 인라인/외부 스크립트 실행을 제한해 XSS 영향도를 줄이는 심층 방어다.",
    },
    {
        "id": "xr-18",
        "question": "HttpOnly 쿠키 속성이 XSS와 관련해 주는 이점은?",
        "options": [
            "쿠키 자체를 암호화",
            "자바스크립트(document.cookie)로 쿠키 접근 차단",
            "쿠키 용량 증가",
            "CSRF 완전 차단",
        ],
        "answer": 1,
        "explanation": "HttpOnly는 스크립트의 쿠키 접근을 막아 XSS로 인한 세션 탈취를 줄인다.",
    },
    {
        "id": "xr-19",
        "question": "Reflected XSS로 공격자가 노리는 대표적 목표가 아닌 것은?",
        "options": [
            "세션 쿠키 탈취",
            "피싱용 가짜 폼 삽입",
            "서버 디스크 포맷",
            "키로깅",
        ],
        "answer": 2,
        "explanation": "XSS는 브라우저 컨텍스트 공격이라 서버 디스크 포맷 같은 서버 직접 파괴와는 거리가 멀다.",
    },
    {
        "id": "xr-20",
        "question": "입력값을 HTML '속성' 안에 넣을 때 특히 주의할 점은?",
        "options": [
            "항상 안전함",
            "인코딩이 전혀 필요 없음",
            "숫자만 허용하면 됨",
            "속성 컨텍스트에 맞는 인코딩과 따옴표 처리 필요",
        ],
        "answer": 3,
        "explanation": "속성 컨텍스트에서는 따옴표 탈출로 이벤트 속성 주입이 가능하므로 별도 인코딩이 필요하다.",
    },
    {
        "id": "xr-21",
        "question": "`javascript:` 스킴이 XSS에 악용되는 맥락은?",
        "options": [
            "href/src 등 URL 속성에 들어가 클릭/로드 시 실행",
            "CSS 색상 지정",
            "이미지 압축",
            "쿠키 설정",
        ],
        "answer": 0,
        "explanation": "`href=\"javascript:...\"` 형태는 링크 실행 시 스크립트가 동작할 수 있다.",
    },
    {
        "id": "xr-22",
        "question": "다음 중 Reflected XSS 탐지에 직접 도움이 되는 활동은?",
        "options": [
            "디스크 용량 점검",
            "입력 파라미터가 응답에 그대로 반사되는지 확인",
            "DB 인덱스 재구성",
            "CPU 온도 측정",
        ],
        "answer": 1,
        "explanation": "입력이 응답 HTML에 그대로 나타나는지 보는 것이 반사형 탐지의 출발점이다.",
    },
    {
        "id": "xr-23",
        "question": "SPA(Vue 등)에서 `v-html` 사용을 지양하는 이유는?",
        "options": [
            "렌더링이 느려서",
            "CSS가 깨져서",
            "원시 HTML을 그대로 삽입해 XSS 위험이 커서",
            "라우팅이 안 돼서",
        ],
        "answer": 2,
        "explanation": "v-html은 문자열을 HTML로 해석해 삽입하므로 검증 없이 쓰면 XSS 위험이 크다.",
    },
    {
        "id": "xr-24",
        "question": "출력 인코딩은 '언제' 수행하는 것이 원칙인가?",
        "options": [
            "입력을 받는 시점에만",
            "서버 시작 시 한 번",
            "로그를 남길 때만",
            "데이터를 출력(렌더링)하는 시점에 컨텍스트에 맞게",
        ],
        "answer": 3,
        "explanation": "같은 데이터도 들어가는 위치가 다르므로 출력 시점의 컨텍스트별 인코딩이 원칙이다.",
    },
    {
        "id": "xr-25",
        "question": "`<script>alert(document.cookie)</script>` 가 성공했을 때의 전형적 위험은?",
        "options": [
            "쿠키 값이 노출/탈취될 수 있음",
            "서버 CPU 과부하",
            "DB가 삭제됨",
            "네트워크 속도 저하",
        ],
        "answer": 0,
        "explanation": "document.cookie 접근으로 세션 쿠키가 노출될 수 있다(HttpOnly면 완화).",
    },
    {
        "id": "xr-26",
        "question": "반사형 XSS에서 '컨텍스트'란 무엇을 의미하는가?",
        "options": [
            "서버의 CPU 상태",
            "입력이 삽입되는 위치(HTML 본문/속성/JS/URL 등)",
            "사용자 국가",
            "브라우저 버전",
        ],
        "answer": 1,
        "explanation": "삽입 위치(컨텍스트)에 따라 필요한 인코딩/이스케이프 방식이 다르다.",
    },
    {
        "id": "xr-27",
        "question": "다음 중 XSS 방어에 '단독으로는' 불충분한 것은?",
        "options": [
            "신뢰할 수 있는 템플릿 자동 이스케이프",
            "컨텍스트별 출력 인코딩",
            "특정 태그만 제거하는 블랙리스트",
            "검증된 새니타이저 라이브러리",
        ],
        "answer": 2,
        "explanation": "블랙리스트는 우회되므로 단독 방어로 부족하다.",
    },
    {
        "id": "xr-28",
        "question": "`<svg onload=alert(1)>` 류 페이로드가 보여주는 교훈은?",
        "options": [
            "svg는 안전하다",
            "인코딩이 불필요하다",
            "이미지에는 코드가 없다",
            "script 외 태그의 이벤트 속성도 실행 벡터가 된다",
        ],
        "answer": 3,
        "explanation": "svg의 onload 등 다양한 태그·이벤트가 실행 경로가 될 수 있다.",
    },
    {
        "id": "xr-29",
        "question": "DOMPurify 같은 라이브러리의 역할은?",
        "options": [
            "허용 목록 기반으로 위험 요소를 제거해 HTML을 안전화",
            "쿠키 암호화",
            "SQL 쿼리 생성",
            "비밀번호 해싱",
        ],
        "answer": 0,
        "explanation": "DOMPurify는 화이트리스트 기반 새니타이즈로 위험 태그/속성을 제거한다.",
    },
    {
        "id": "xr-30",
        "question": "반사형 XSS를 '저장 없이' 1회성으로 만드는 요소는?",
        "options": [
            "입력이 DB에 기록됨",
            "입력이 해당 요청의 응답에만 포함됨",
            "입력이 파일에 저장됨",
            "입력이 세션에 영구 저장됨",
        ],
        "answer": 1,
        "explanation": "입력이 그 요청의 응답에만 들어가므로 지속성이 없다.",
    },
    {
        "id": "xr-31",
        "question": "URL 파라미터를 화면에 표시할 때 안전한 처리는?",
        "options": [
            "그대로 innerHTML에 삽입",
            "eval로 실행",
            "textContent 또는 출력 인코딩 후 표시",
            "쿠키에 저장",
        ],
        "answer": 2,
        "explanation": "textContent/인코딩을 쓰면 값이 코드로 해석되지 않는다.",
    },
    {
        "id": "xr-32",
        "question": "다음 중 '반사 지점'이 될 수 있는 입력이 아닌 것은?",
        "options": [
            "검색어 쿼리스트링",
            "에러 메시지에 되비치는 파라미터",
            "User-Agent를 그대로 출력하는 페이지",
            "서버 내부 상수 문자열",
        ],
        "answer": 3,
        "explanation": "서버 내부 상수는 사용자 입력이 아니므로 반사 지점이 아니다.",
    },
    {
        "id": "xr-33",
        "question": "`htmlspecialchars`가 기본적으로 인코딩하지 않을 수 있는 문자는?",
        "options": [
            "작은따옴표(기본 플래그에 따라)",
            "`>`",
            "`<`",
            "`&`",
        ],
        "answer": 0,
        "explanation": "PHP htmlspecialchars는 플래그에 따라 작은따옴표를 인코딩하지 않을 수 있어 ENT_QUOTES가 권장된다.",
    },
    {
        "id": "xr-34",
        "question": "XSS와 CSRF의 핵심 차이는?",
        "options": [
            "둘은 같은 취약점이다",
            "XSS는 스크립트 실행, CSRF는 피해자 권한의 위조 요청",
            "CSRF가 더 오래된 자바스크립트 취약점",
            "XSS는 서버에서만 발생",
        ],
        "answer": 1,
        "explanation": "XSS는 스크립트 실행 문제, CSRF는 인증된 상태를 악용한 요청 위조 문제다.",
    },
    {
        "id": "xr-35",
        "question": "반사형 XSS 점검 시 가장 먼저 시도하는 무해한 표식(canary)은?",
        "options": [
            "DB를 덤프",
            "서버를 재부팅",
            "임의 고유 문자열을 넣고 응답에 그대로 나오는지 확인",
            "포트 스캔",
        ],
        "answer": 2,
        "explanation": "고유 문자열의 반사 여부로 삽입 지점과 인코딩 상태를 파악한다.",
    },
    {
        "id": "xr-36",
        "question": "다음 중 XSS 영향 '완화(심층 방어)'에 해당하는 것은?",
        "options": [
            "모든 자바스크립트 비활성화 요구",
            "출력 인코딩만 하면 끝",
            "입력을 아예 받지 않음",
            "CSP, HttpOnly, SameSite 등 병행",
        ],
        "answer": 3,
        "explanation": "인코딩을 기본으로 하되 CSP·쿠키 속성 등으로 영향도를 줄이는 심층 방어가 바람직하다.",
    },
    {
        "id": "xr-37",
        "question": "`onerror`, `onload`, `onmouseover` 같은 속성의 공통점은?",
        "options": [
            "이벤트 발생 시 자바스크립트를 실행하는 이벤트 핸들러",
            "CSS 속성이다",
            "이미지 포맷이다",
            "HTTP 헤더다",
        ],
        "answer": 0,
        "explanation": "이들은 특정 이벤트에 스크립트를 실행하는 HTML 이벤트 핸들러 속성이다.",
    },
    {
        "id": "xr-38",
        "question": "반사형 XSS가 '서버 로그에는 남지만' 다른 사용자에게 지속 피해를 주지 않는 이유는?",
        "options": [
            "서버가 로그를 지워서",
            "요청별 1회성이고 저장되지 않아서",
            "자바스크립트가 로그를 못 남겨서",
            "HTTPS 때문",
        ],
        "answer": 1,
        "explanation": "저장되지 않으므로 그 링크를 클릭한 사람에게만 1회 작동한다.",
    },
    {
        "id": "xr-39",
        "question": "입력을 '검증'할 때 더 안전한 접근은?",
        "options": [
            "블랙리스트(금지 목록)",
            "길이만 제한",
            "화이트리스트(허용 목록)",
            "검증 생략",
        ],
        "answer": 2,
        "explanation": "허용 형식만 통과시키는 화이트리스트가 블랙리스트보다 안전하다.",
    },
    {
        "id": "xr-40",
        "question": "다음 중 Reflected XSS 시나리오로 가장 적절한 것은?",
        "options": [
            "방화벽 규칙 적용",
            "정적 이미지 CDN 서빙",
            "DB 백업 스크립트",
            "검색 결과 페이지가 검색어를 인코딩 없이 그대로 출력",
        ],
        "answer": 3,
        "explanation": "검색어가 그대로 반사되는 페이지는 전형적인 반사형 XSS 지점이다.",
    },
    {
        "id": "xr-41",
        "question": "자바스크립트 문자열 컨텍스트에 값을 넣을 때 위험한 실수는?",
        "options": [
            "JSON 인코딩/적절한 이스케이프 없이 문자열에 직접 삽입",
            "textContent 사용",
            "상수만 사용",
            "숫자 검증",
        ],
        "answer": 0,
        "explanation": "JS 문자열에 사용자 값을 그대로 넣으면 따옴표 탈출로 코드 주입이 가능하다.",
    },
    {
        "id": "xr-42",
        "question": "다음 중 '안전 단계(Impossible)'에서 어떤 페이로드도 실패하는 이유는?",
        "options": [
            "서버가 느려서",
            "출력 인코딩으로 태그가 글자로만 표시되어서",
            "입력이 차단되어서",
            "자바스크립트가 꺼져서",
        ],
        "answer": 1,
        "explanation": "htmlspecialchars 적용으로 태그가 생성되지 않아 실행될 코드가 없다.",
    },
    {
        "id": "xr-43",
        "question": "반사형 XSS 방어에서 '템플릿 엔진 자동 이스케이프'의 장점은?",
        "options": [
            "DB 용량 절감",
            "서버가 빨라짐",
            "개발자가 매번 수동 처리하지 않아도 기본 인코딩이 적용됨",
            "쿠키 자동 삭제",
        ],
        "answer": 2,
        "explanation": "자동 이스케이프 템플릿은 누락 위험을 줄여 준다.",
    },
    {
        "id": "xr-44",
        "question": "`&lt;script&gt;` 가 화면에 그대로 '글자'로 보인다면?",
        "options": [
            "XSS가 실행된 것",
            "CSP 위반",
            "서버 오류",
            "출력 인코딩이 적용되어 방어된 상태",
        ],
        "answer": 3,
        "explanation": "엔티티로 표시된다는 것은 인코딩이 적용되어 태그로 해석되지 않았다는 뜻이다.",
    },
    {
        "id": "xr-45",
        "question": "반사형 XSS와 가장 관련 깊은 OWASP 범주는?",
        "options": [
            "Injection(인젝션) 계열",
            "암호화 실패",
            "접근 통제 실패",
            "서버 설정 오류",
        ],
        "answer": 0,
        "explanation": "XSS는 넓게 보아 인젝션 계열(클라이언트 측 코드 주입)로 분류된다.",
    },
    {
        "id": "xr-46",
        "question": "다음 중 XSS 방어로 '잘못된' 믿음은?",
        "options": [
            "컨텍스트별 인코딩이 필요하다",
            "`<script>` 문자열만 지우면 안전하다",
            "CSP는 심층 방어다",
            "HttpOnly는 쿠키 탈취를 완화한다",
        ],
        "answer": 1,
        "explanation": "특정 문자열만 제거하는 방식은 대소문자·다른 태그로 우회된다.",
    },
    {
        "id": "xr-47",
        "question": "URL에 페이로드를 넣어 공유하는 반사형 공격을 줄이는 서버 측 조치는?",
        "options": [
            "쿠키 수명 연장",
            "URL 단축",
            "파라미터 값을 출력 시 인코딩",
            "로그 비활성화",
        ],
        "answer": 2,
        "explanation": "결국 출력 시 인코딩이 핵심 방어다.",
    },
    {
        "id": "xr-48",
        "question": "다음 중 '반사형'이라는 이름의 유래로 가장 맞는 설명은?",
        "options": [
            "DB가 결과를 반사해서",
            "빛을 반사해서",
            "서버가 요청을 반사해서",
            "입력이 거울처럼 그 응답에 되비쳐 돌아오기 때문",
        ],
        "answer": 3,
        "explanation": "요청한 값이 즉시 응답에 반사되어 돌아오는 특성에서 유래했다.",
    },
    {
        "id": "xr-49",
        "question": "XSS 페이로드의 성공을 '브라우저에서' 확인하는 가장 직접적 신호는?",
        "options": [
            "주입한 스크립트(alert 등)가 실제로 실행됨",
            "서버 응답 코드 200",
            "DB 레코드 증가",
            "CPU 사용률 상승",
        ],
        "answer": 0,
        "explanation": "스크립트가 브라우저에서 실제로 실행되는지가 XSS 성립의 직접 증거다.",
    },
    {
        "id": "xr-50",
        "question": "반사형 XSS 종합: 가장 올바른 방어 조합은?",
        "options": [
            "입력 길이 제한만",
            "출력 인코딩 + 컨텍스트 인지 + CSP/HttpOnly 등 심층 방어",
            "HTTPS만 적용",
            "자바스크립트 금지 안내",
        ],
        "answer": 1,
        "explanation": "컨텍스트별 출력 인코딩을 기본으로 CSP·쿠키 속성 등을 병행하는 것이 바람직하다.",
    },
]
