"""XSS (DOM) 미션 퀴즈 문항 은행 (50문항)."""

QUESTIONS = [
    {
        "id": "xd-01",
        "question": "DOM-based XSS의 핵심 정의는?",
        "options": [
            "클라이언트 자바스크립트가 데이터를 위험한 싱크에 넣어 실행",
            "서버가 입력을 응답에 반사",
            "DB에 저장된 값이 실행",
            "HTTP 헤더 조작",
        ],
        "answer": 0,
        "explanation": "DOM XSS는 서버가 아니라 브라우저의 JS가 값을 위험한 싱크에 넣을 때 발생한다.",
    },
    {
        "id": "xd-02",
        "question": "DOM XSS가 Reflected/Stored와 근본적으로 다른 점은?",
        "options": [
            "항상 DB가 필요",
            "서버 응답 자체에 페이로드가 없어도 발생 가능",
            "자바스크립트가 필요 없음",
            "HTTPS에서만 발생",
        ],
        "answer": 1,
        "explanation": "취약점이 전적으로 클라이언트 측 DOM 처리에서 생겨 서버 응답에 흔적이 없을 수 있다.",
    },
    {
        "id": "xd-03",
        "question": "DOM XSS에서 '소스(source)'란?",
        "options": [
            "CSS 파일",
            "서버의 데이터베이스",
            "공격자가 값을 넣을 수 있는 입력 지점(location.hash 등)",
            "쿠키 서명 키",
        ],
        "answer": 2,
        "explanation": "소스는 공격자 제어 데이터가 들어오는 입구(URL, location.hash, document.referrer 등)다.",
    },
    {
        "id": "xd-04",
        "question": "DOM XSS에서 '싱크(sink)'란?",
        "options": [
            "데이터를 저장하는 서버",
            "로그 파일",
            "네트워크 소켓",
            "값을 받아 실행/렌더링하는 위험한 API(innerHTML 등)",
        ],
        "answer": 3,
        "explanation": "싱크는 값을 DOM에 반영/실행하는 지점으로, innerHTML·document.write·eval 등이 대표적이다.",
    },
    {
        "id": "xd-05",
        "question": "다음 중 위험한 싱크가 아닌 것은?",
        "options": [
            "element.textContent",
            "document.write",
            "element.innerHTML",
            "eval",
        ],
        "answer": 0,
        "explanation": "textContent는 값을 HTML로 해석하지 않고 글자로만 넣으므로 안전하다.",
    },
    {
        "id": "xd-06",
        "question": "`location.hash`가 DOM XSS 소스로 자주 쓰이는 이유는?",
        "options": [
            "항상 암호화됨",
            "서버로 전송되지 않아 서버 필터를 우회",
            "쿠키에 저장됨",
            "CSS에서 읽힘",
        ],
        "answer": 1,
        "explanation": "# 뒤 값은 서버로 전송되지 않아 클라이언트에서만 처리되며 서버 측 방어를 비껴간다.",
    },
    {
        "id": "xd-07",
        "question": "DVWA DOM XSS에서 조작 대상이 되는 파라미터는?",
        "options": [
            "password",
            "csrf_token",
            "default(언어 선택)",
            "session_id",
        ],
        "answer": 2,
        "explanation": "DVWA DOM XSS는 `?default=` 언어 선택 값을 클라이언트 JS가 처리한다.",
    },
    {
        "id": "xd-08",
        "question": "`document.write`로 사용자 값을 쓰는 코드가 위험한 이유는?",
        "options": [
            "느려서",
            "서버를 호출해서",
            "쿠키를 지워서",
            "받은 문자열을 HTML로 그대로 해석하기 때문",
        ],
        "answer": 3,
        "explanation": "document.write는 문자열을 HTML로 파싱하므로 태그가 실행될 수 있다.",
    },
    {
        "id": "xd-09",
        "question": "innerHTML에 삽입된 `<script>` 태그가 '실행되지 않는' 이유는?",
        "options": [
            "브라우저가 innerHTML로 추가된 script를 실행하지 않도록 규정",
            "script가 항상 차단됨",
            "서버가 막아서",
            "CSP 때문",
        ],
        "answer": 0,
        "explanation": "HTML5 명세상 innerHTML로 삽입된 script는 실행되지 않아, 공격자는 이벤트 핸들러 등을 쓴다.",
    },
    {
        "id": "xd-10",
        "question": "innerHTML 싱크를 노릴 때 흔히 쓰는 우회 페이로드는?",
        "options": [
            "`SELECT * FROM users`",
            "`<img src=x onerror=alert(1)>`",
            "`; rm -rf /`",
            "`' OR '1'='1`",
        ],
        "answer": 1,
        "explanation": "script가 실행 안 되므로 로드 실패 이벤트 핸들러(onerror) 등을 이용한다.",
    },
    {
        "id": "xd-11",
        "question": "`<details open ontoggle=alert(1)>` 페이로드의 특징은?",
        "options": [
            "클릭해야만 실행",
            "이미지 로드 시 실행",
            "열림 상태로 자동 toggle 이벤트가 발생해 실행",
            "항상 차단됨",
        ],
        "answer": 2,
        "explanation": "open 상태의 details는 ontoggle이 자동 발생해 상호작용 없이도 실행된다.",
    },
    {
        "id": "xd-12",
        "question": "DOM XSS의 가장 안전한 기본 방어는?",
        "options": [
            "서버 재시작",
            "입력 길이 제한",
            "쿠키 삭제",
            "innerHTML 대신 textContent 사용",
        ],
        "answer": 3,
        "explanation": "textContent는 HTML로 해석하지 않으므로 DOM XSS를 원천 차단한다.",
    },
    {
        "id": "xd-13",
        "question": "클라이언트 측 필터를 신뢰하기 어려운 이유는?",
        "options": [
            "공격자가 브라우저에서 코드를 읽고 우회할 수 있어서",
            "느려서",
            "서버가 무시해서",
            "CSS가 가려서",
        ],
        "answer": 0,
        "explanation": "클라이언트 JS 필터는 공격자도 그대로 볼 수 있어 우회가 쉽다.",
    },
    {
        "id": "xd-14",
        "question": "DOMPurify의 역할은?",
        "options": [
            "쿠키 암호화",
            "허용 목록 기반으로 위험 태그·속성을 제거해 HTML 새니타이즈",
            "SQL 생성",
            "토큰 발급",
        ],
        "answer": 1,
        "explanation": "DOMPurify는 신뢰 가능한 요소만 남겨 DOM XSS를 방지한다.",
    },
    {
        "id": "xd-15",
        "question": "다음 중 DOM XSS 소스로 볼 수 있는 것은?",
        "options": [
            "빌드 시 결정된 정적 텍스트",
            "서버 상수",
            "location.search / location.hash / document.referrer",
            "DB 스키마",
        ],
        "answer": 2,
        "explanation": "URL 쿼리·해시·referrer 등 공격자 영향 데이터가 소스다.",
    },
    {
        "id": "xd-16",
        "question": "DOM XSS가 '서버 로그에 잘 안 남는' 이유는?",
        "options": [
            "서버가 로그를 지워서",
            "자바스크립트가 로그를 못 남겨서",
            "HTTPS 때문",
            "페이로드가 location.hash 등 클라이언트에서만 처리되어서",
        ],
        "answer": 3,
        "explanation": "해시 기반 등은 서버로 가지 않아 서버 로그에 남지 않을 수 있다.",
    },
    {
        "id": "xd-17",
        "question": "`eval(userInput)` 패턴이 위험한 이유는?",
        "options": [
            "문자열을 코드로 실행하기 때문",
            "항상 숫자로 변환되어서",
            "서버에서만 실행되어서",
            "쿠키를 읽어서",
        ],
        "answer": 0,
        "explanation": "eval은 입력 문자열을 코드로 실행하므로 임의 스크립트 실행 위험이 있다.",
    },
    {
        "id": "xd-18",
        "question": "`element.setAttribute('href', userInput)` 에서 주의할 스킴은?",
        "options": [
            "https:",
            "javascript:",
            "mailto:",
            "data:text/plain",
        ],
        "answer": 1,
        "explanation": "href에 javascript: 스킴이 들어가면 클릭 시 스크립트가 실행될 수 있다.",
    },
    {
        "id": "xd-19",
        "question": "DOM XSS 방어에서 '컨텍스트 인지 인코딩'이 필요한 이유는?",
        "options": [
            "쿠키 때문",
            "속도 때문",
            "HTML/속성/JS/URL 각각 안전 처리 방식이 다르기 때문",
            "DB 때문",
        ],
        "answer": 2,
        "explanation": "값이 들어가는 DOM 위치마다 요구되는 이스케이프가 달라서다.",
    },
    {
        "id": "xd-20",
        "question": "다음 중 '안전한 싱크'에 가까운 것은?",
        "options": [
            "document.write",
            "innerHTML",
            "outerHTML",
            "textContent, value 설정(일부)",
        ],
        "answer": 3,
        "explanation": "textContent 등은 HTML 파싱 없이 값을 다뤄 상대적으로 안전하다.",
    },
    {
        "id": "xd-21",
        "question": "DVWA DOM XSS Medium(‘<script’ 차단) 우회로 적절한 것은?",
        "options": [
            "`<img src=x onerror=alert(1)>`",
            "`<script>alert(1)</script>`",
            "대문자 SQL",
            "쿠키 조작",
        ],
        "answer": 0,
        "explanation": "script 문자열만 막으므로 다른 태그의 이벤트 핸들러로 우회한다.",
    },
    {
        "id": "xd-22",
        "question": "DVWA DOM XSS High 단계에서 자주 쓰는 우회 기법은?",
        "options": [
            "SQL UNION",
            "URL 프래그먼트(#) 활용 또는 허용 목록 밖 값",
            "파일 업로드",
            "DNS 조작",
        ],
        "answer": 1,
        "explanation": "High는 화이트리스트/서버 검사를 두므로 # 프래그먼트나 목록 밖 경로로 우회한다.",
    },
    {
        "id": "xd-23",
        "question": "DOM XSS를 테스트할 때 브라우저 개발자도구로 확인할 핵심은?",
        "options": [
            "CPU 온도",
            "디스크 용량",
            "소스→싱크 데이터 흐름(어디서 들어와 어디서 실행되는지)",
            "DNS TTL",
        ],
        "answer": 2,
        "explanation": "입력(소스)이 어떤 싱크에 도달하는지 추적하는 것이 핵심이다.",
    },
    {
        "id": "xd-24",
        "question": "다음 중 DOM XSS와 가장 거리가 먼 방어는?",
        "options": [
            "위험 싱크 회피",
            "textContent 사용",
            "DOMPurify 적용",
            "서버 측 SQL 파라미터 바인딩",
        ],
        "answer": 3,
        "explanation": "SQL 바인딩은 SQLi 방어로, DOM XSS와 직접 관련이 없다.",
    },
    {
        "id": "xd-25",
        "question": "`innerHTML +=` 로 사용자 값을 누적하는 코드의 문제는?",
        "options": [
            "매번 HTML로 재파싱되어 주입 위험",
            "메모리만 쓴다",
            "항상 안전",
            "서버 부하",
        ],
        "answer": 0,
        "explanation": "innerHTML은 값을 HTML로 해석하므로 누적 삽입도 주입 위험이 있다.",
    },
    {
        "id": "xd-26",
        "question": "CSP가 DOM XSS에 주는 효과는?",
        "options": [
            "입력 자동 삭제",
            "인라인 스크립트/eval 제한으로 실행을 어렵게 함",
            "쿠키 암호화",
            "SQLi 차단",
        ],
        "answer": 1,
        "explanation": "CSP로 unsafe-inline/eval을 막으면 DOM XSS 성공을 크게 낮춘다.",
    },
    {
        "id": "xd-27",
        "question": "다음 중 DOM XSS 소스가 될 수 없는 것은?",
        "options": [
            "window.name",
            "location.hash",
            "서버에서만 설정되는 상수 배너 텍스트",
            "document.referrer",
        ],
        "answer": 2,
        "explanation": "공격자가 제어할 수 없는 서버 상수는 소스가 아니다.",
    },
    {
        "id": "xd-28",
        "question": "`jQuery.html(userInput)` 사용의 위험성은?",
        "options": [
            "서버에서 실행",
            "항상 안전",
            "숫자만 허용",
            "내부적으로 innerHTML을 써 HTML로 해석되어 주입 위험",
        ],
        "answer": 3,
        "explanation": ".html()은 innerHTML 계열이라 사용자 값 삽입 시 위험하다. .text()가 안전하다.",
    },
    {
        "id": "xd-29",
        "question": "DOM XSS 방어로 '가장 권장되는' 접근은?",
        "options": [
            "안전한 싱크(textContent) + 필요한 경우 검증된 새니타이저",
            "블랙리스트 키워드 제거",
            "입력 대문자화",
            "쿠키 수명 단축",
        ],
        "answer": 0,
        "explanation": "위험 싱크를 피하고, 불가피하면 DOMPurify 같은 새니타이저를 쓰는 것이 권장된다.",
    },
    {
        "id": "xd-30",
        "question": "`document.location = userInput` 패턴의 위험은?",
        "options": [
            "항상 안전",
            "javascript: 스킴 등으로 스크립트 실행/오픈 리다이렉트",
            "CSS 깨짐",
            "DB 변경",
        ],
        "answer": 1,
        "explanation": "리다이렉트 대상에 사용자 값을 그대로 쓰면 스킴 악용·오픈 리다이렉트 위험이 있다.",
    },
    {
        "id": "xd-31",
        "question": "다음 중 DOM XSS 성공을 직접 증명하는 신호는?",
        "options": [
            "DB row 증가",
            "HTTP 200",
            "주입 스크립트가 브라우저에서 실제 실행",
            "서버 CPU 상승",
        ],
        "answer": 2,
        "explanation": "클라이언트에서 스크립트가 실제로 실행되는지가 성립 증거다.",
    },
    {
        "id": "xd-32",
        "question": "`innerHTML` 대신 `textContent`를 쓰면 생기는 변화는?",
        "options": [
            "서버 호출 발생",
            "성능이 급락",
            "쿠키가 삭제됨",
            "태그가 글자로만 표시되어 실행되지 않음",
        ],
        "answer": 3,
        "explanation": "textContent는 HTML로 해석하지 않으므로 태그가 실행되지 않는다.",
    },
    {
        "id": "xd-33",
        "question": "DOM XSS에서 '프레임워크 자동 이스케이프'가 주는 이점은?",
        "options": [
            "기본 바인딩 시 값이 자동으로 인코딩되어 안전",
            "서버가 빨라짐",
            "DB 절약",
            "쿠키 암호화",
        ],
        "answer": 0,
        "explanation": "Vue/React 등은 기본 텍스트 바인딩을 이스케이프하여 안전하다(v-html 제외).",
    },
    {
        "id": "xd-34",
        "question": "Vue에서 DOM XSS를 유발할 수 있는 대표 기능은?",
        "options": [
            "v-if",
            "v-html",
            "v-for",
            "computed",
        ],
        "answer": 1,
        "explanation": "v-html은 원시 HTML을 삽입하므로 검증 없이 쓰면 XSS 위험이 크다.",
    },
    {
        "id": "xd-35",
        "question": "다음 중 '소스→싱크' 흐름이 안전하게 끝나는 경우는?",
        "options": [
            "location.search → document.write",
            "location.hash → innerHTML",
            "location.hash → textContent",
            "window.name → eval",
        ],
        "answer": 2,
        "explanation": "textContent로 끝나면 HTML 해석이 없어 안전하다.",
    },
    {
        "id": "xd-36",
        "question": "DOM XSS 점검 시 'Sources and Sinks'를 보는 자동화 도구의 목적은?",
        "options": [
            "이미지 압축",
            "디스크 정리",
            "SQL 최적화",
            "위험한 데이터 흐름(taint)을 추적",
        ],
        "answer": 3,
        "explanation": "taint 분석으로 소스에서 싱크로 가는 위험 흐름을 찾는다.",
    },
    {
        "id": "xd-37",
        "question": "`setTimeout(userInput, 1000)` 에 문자열을 넘기면?",
        "options": [
            "문자열이 코드로 평가되어 실행될 수 있음",
            "항상 숫자",
            "항상 무시",
            "서버 실행",
        ],
        "answer": 0,
        "explanation": "문자열 인자를 받은 setTimeout은 eval처럼 동작해 위험하다.",
    },
    {
        "id": "xd-38",
        "question": "DVWA DOM XSS Impossible 단계가 안전한 이유는?",
        "options": [
            "서버가 느려서",
            "위험 싱크를 피하고 안전하게 값을 처리",
            "입력이 차단되어서",
            "자바스크립트가 꺼져서",
        ],
        "answer": 1,
        "explanation": "안전 단계는 textContent 등으로 값을 코드로 해석하지 않게 처리한다.",
    },
    {
        "id": "xd-39",
        "question": "다음 중 DOM XSS 위험을 '높이는' 코딩 습관은?",
        "options": [
            "허용 목록 검증",
            "textContent 사용",
            "URL 값 검증 없이 innerHTML에 삽입",
            "DOMPurify 적용",
        ],
        "answer": 2,
        "explanation": "검증 없는 innerHTML 삽입이 가장 전형적인 위험 패턴이다.",
    },
    {
        "id": "xd-40",
        "question": "`document.referrer`를 화면에 표시할 때 안전한 방법은?",
        "options": [
            "쿠키에 저장",
            "innerHTML로 바로 삽입",
            "eval로 처리",
            "textContent로 출력하거나 인코딩",
        ],
        "answer": 3,
        "explanation": "referrer도 공격자 영향 가능 데이터이므로 안전 싱크/인코딩이 필요하다.",
    },
    {
        "id": "xd-41",
        "question": "DOM XSS와 Reflected XSS를 함께 방어하려면?",
        "options": [
            "서버 출력 인코딩 + 클라이언트 안전 싱크 둘 다",
            "서버만 신경",
            "클라이언트만 신경",
            "둘 다 불필요",
        ],
        "answer": 0,
        "explanation": "두 취약점은 발생 위치가 달라 서버·클라이언트 양쪽 방어가 필요하다.",
    },
    {
        "id": "xd-42",
        "question": "다음 중 '안전한 URL 처리'로 적절한 것은?",
        "options": [
            "모든 스킴 허용",
            "허용 스킴(http/https) 화이트리스트 검증",
            "javascript: 허용",
            "검증 생략",
        ],
        "answer": 1,
        "explanation": "허용 스킴만 통과시키면 javascript: 등 악성 스킴을 막는다.",
    },
    {
        "id": "xd-43",
        "question": "DOM XSS에서 'HTML 컨텍스트'와 'JS 컨텍스트'를 구분해야 하는 이유는?",
        "options": [
            "쿠키 차이",
            "속도 차이",
            "각 컨텍스트의 이스케이프 규칙이 다르기 때문",
            "서버 차이",
        ],
        "answer": 2,
        "explanation": "HTML 엔티티 인코딩과 JS 문자열 이스케이프는 서로 다른 규칙이다.",
    },
    {
        "id": "xd-44",
        "question": "`innerHTML`로 삽입한 콘텐츠의 이벤트 핸들러가 실행되는 이유는?",
        "options": [
            "CSP 때문",
            "브라우저 버그",
            "서버가 실행",
            "이벤트 속성은 파싱 시 등록되어 조건 충족 시 실행",
        ],
        "answer": 3,
        "explanation": "onerror/ontoggle 등 속성은 DOM 구성 시 등록되어 해당 이벤트에 실행된다.",
    },
    {
        "id": "xd-45",
        "question": "다음 중 DOM XSS 완화에 직접 기여하지 않는 것은?",
        "options": [
            "데이터베이스 인덱스 추가",
            "CSP 적용",
            "안전 싱크 사용",
            "DOMPurify 적용",
        ],
        "answer": 0,
        "explanation": "DB 인덱스는 성능 요소로 DOM XSS와 무관하다.",
    },
    {
        "id": "xd-46",
        "question": "클라이언트 라우팅(SPA)에서 해시/쿼리 값을 렌더링할 때 원칙은?",
        "options": [
            "항상 innerHTML 사용",
            "바인딩 시 자동 이스케이프에 맡기고 v-html/ innerHTML 회피",
            "eval로 처리",
            "검증 생략",
        ],
        "answer": 1,
        "explanation": "SPA 기본 바인딩은 이스케이프되므로 원시 HTML 삽입을 피해야 한다.",
    },
    {
        "id": "xd-47",
        "question": "DOM XSS에서 '화이트리스트' 접근의 예로 적절한 것은?",
        "options": [
            "script만 제거",
            "모든 입력 허용",
            "허용된 언어 값(English/Korean 등)만 처리",
            "길이만 제한",
        ],
        "answer": 2,
        "explanation": "허용 값 집합만 받아들이면 임의 페이로드가 걸러진다.",
    },
    {
        "id": "xd-48",
        "question": "`a.href = userInput` 후 사용자가 링크를 클릭하면?",
        "options": [
            "쿠키 삭제",
            "항상 안전",
            "서버가 차단",
            "javascript: 스킴이면 스크립트 실행 가능",
        ],
        "answer": 3,
        "explanation": "href에 악성 스킴이 들어가면 클릭 시 실행될 수 있다.",
    },
    {
        "id": "xd-49",
        "question": "DOM XSS 종합 방어로 '가장 올바른' 조합은?",
        "options": [
            "안전 싱크(textContent) + 새니타이저 + CSP 심층 방어",
            "입력 길이 제한만",
            "HTTPS만",
            "자바스크립트 비활성 안내",
        ],
        "answer": 0,
        "explanation": "위험 싱크 회피를 기본으로 새니타이저·CSP를 병행한다.",
    },
    {
        "id": "xd-50",
        "question": "DOM XSS를 한 문장으로 요약하면?",
        "options": [
            "DB에 저장되어 반복 실행되는 XSS",
            "서버가 아닌 브라우저 JS가 값을 위험하게 다뤄 생기는 XSS",
            "서버가 입력을 반사하는 XSS",
            "SQL 주입의 일종",
        ],
        "answer": 1,
        "explanation": "DOM XSS는 클라이언트 측 데이터 처리 과정에서 발생하는 XSS다.",
    },
]
