events {}

http {
  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend:5000/api/;
      proxy_set_header Host $host;
    }

    location /pdf/ {
      proxy_pass http://backend:5000/pdf/;
      proxy_set_header Host $host;
    }

    location /practice/ {
      proxy_pass http://backend:5000/practice/;
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://frontend:5173/;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}
