"""add course slug and difficulty

Revision ID: 338ece05201e
Revises: b1a9b6c8c456
Create Date: 2026-09-25 01:17:29.581171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338ece05201e'
down_revision = 'b1a9b6c8c456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Enum('초급', '중급', '고급', name='course_difficulty'), nullable=True))
        batch_op.create_unique_constraint('uq_courses_slug', ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_courses_slug', type_='unique')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
